

MATCH_RECORD_SEEDS = [
    {
        'user': 'plant_lover1',
        'matched_user': 'expert_succulent',
        'match_type': 'expert',
        'similarity_score': 0.85,
        'match_reason': '用户对多肉植物感兴趣且存在浇水问题，匹配多肉养护专家',
        'matched_tags': ['多肉植物', '浇水问题'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '专家回复很详细，帮我解决了熊童子黑腐的问题',
    },
    {
        'user': 'plant_lover1',
        'matched_user': 'succulent_fan',
        'match_type': 'peer',
        'similarity_score': 0.72,
        'match_reason': '同为多肉爱好者，可以交流养护经验',
        'matched_tags': ['多肉植物'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '聊了很多叶插的经验，收获不少',
    },
    {
        'user': 'office_plant',
        'matched_user': 'expert_foliage',
        'match_type': 'expert',
        'similarity_score': 0.90,
        'match_reason': '用户在办公室养观叶植物且光照不足，匹配观叶植物专家',
        'matched_tags': ['观叶植物', '光照不足'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '推荐了几种耐阴植物，白掌的养护建议特别实用',
    },
    {
        'user': 'office_plant',
        'matched_user': 'green_thumb',
        'match_type': 'peer',
        'similarity_score': 0.68,
        'match_reason': '都在室内养观叶植物，有共同话题',
        'matched_tags': ['观叶植物', '室内'],
        'is_contacted': False,
    },
    {
        'user': 'balcony_garden',
        'matched_user': 'expert_flower',
        'match_type': 'expert',
        'similarity_score': 0.88,
        'match_reason': '用户阳台养开花植物和香草，匹配花卉养护专家',
        'matched_tags': ['开花植物', '阳台花园'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '月季修剪和追肥的建议非常专业',
    },
    {
        'user': 'flower_mama',
        'matched_user': 'expert_flower',
        'match_type': 'expert',
        'similarity_score': 0.82,
        'match_reason': '用户养开花植物且需要花期管理指导',
        'matched_tags': ['开花植物', '花期管理'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '绣球调色的方法讲得很清楚',
    },
    {
        'user': 'flower_mama',
        'matched_user': 'balcony_garden',
        'match_type': 'peer',
        'similarity_score': 0.75,
        'match_reason': '同为阳台养花爱好者，养了相似的品种',
        'matched_tags': ['开花植物', '阳台'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '交流了很多月季和绣球的养护心得',
    },
    {
        'user': 'fern_lover',
        'matched_user': 'expert_foliage',
        'match_type': 'expert',
        'similarity_score': 0.87,
        'match_reason': '用户喜欢蕨类和观叶植物，匹配观叶植物专家',
        'matched_tags': ['蕨类植物', '观叶植物'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '鹿角蕨上板的建议帮了大忙',
    },
    {
        'user': 'herb_garden',
        'matched_user': 'expert_flower',
        'match_type': 'expert',
        'similarity_score': 0.70,
        'match_reason': '用户养香草植物，花卉专家也有相关经验',
        'matched_tags': ['香草植物'],
        'is_contacted': False,
    },
    {
        'user': 'herb_garden',
        'matched_user': 'balcony_garden',
        'match_type': 'peer',
        'similarity_score': 0.73,
        'match_reason': '都在阳台种植香草，养护环境相似',
        'matched_tags': ['香草植物', '阳台'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '分享了迷迭香和罗勒的种植经验',
    },
    {
        'user': 'cactus_king',
        'matched_user': 'expert_succulent',
        'match_type': 'expert',
        'similarity_score': 0.86,
        'match_reason': '用户养仙人掌和多肉，匹配多肉养护专家',
        'matched_tags': ['仙人掌', '多肉植物'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '仙人掌冬季养护的建议很有帮助',
    },
    {
        'user': 'cactus_king',
        'matched_user': 'succulent_fan',
        'match_type': 'peer',
        'similarity_score': 0.80,
        'match_reason': '都是多肉和仙人掌爱好者，品种收集兴趣重合',
        'matched_tags': ['仙人掌', '多肉植物', '品种收集'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '交换了几个品种的小崽，太开心了',
    },
    {
        'user': 'weekend_gardener',
        'matched_user': 'expert_succulent',
        'match_type': 'expert',
        'similarity_score': 0.78,
        'match_reason': '用户养多肉且偏好耐旱品种',
        'matched_tags': ['多肉植物', '仙人掌'],
        'is_contacted': False,
    },
    {
        'user': 'weekend_gardener',
        'matched_user': 'succulent_fan',
        'match_type': 'peer',
        'similarity_score': 0.71,
        'match_reason': '都在阳台养多肉，有共同的品种',
        'matched_tags': ['多肉植物', '阳台'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '送了我一些叶片练习叶插',
    },
    {
        'user': 'green_thumb',
        'matched_user': 'expert_foliage',
        'match_type': 'expert',
        'similarity_score': 0.83,
        'match_reason': '用户养观叶和藤蔓植物，匹配观叶专家',
        'matched_tags': ['观叶植物', '藤蔓植物'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '蕨类上板的教程非常实用',
    },
    {
        'user': 'green_thumb',
        'matched_user': 'fern_lover',
        'match_type': 'peer',
        'similarity_score': 0.69,
        'match_reason': '都喜欢室内观叶植物',
        'matched_tags': ['观叶植物', '室内'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '一起讨论了雨林缸的布局',
    },

    
    {
        'user': 'tropical_fan',
        'matched_user': 'expert_foliage',
        'match_type': 'expert',
        'similarity_score': 0.92,
        'match_reason': '热带植物收藏丰富，匹配观叶植物专家',
        'matched_tags': ['热带植物', '观叶植物', '攀爬植物'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '合果芋攀爬柱的做法讲解得很清楚',
    },
    {
        'user': 'tropical_fan',
        'matched_user': 'fern_lover',
        'match_type': 'peer',
        'similarity_score': 0.78,
        'match_reason': '都喜欢鹿角蕨板植和热带雨林风格',
        'matched_tags': ['鹿角蕨', '板植', '热带植物'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '交流了鹿角蕨的水苔配比，受益match',
    },
    {
        'user': 'tropical_fan',
        'matched_user': 'green_thumb',
        'match_type': 'peer',
        'similarity_score': 0.74,
        'match_reason': '都养常春藤和观叶植物',
        'matched_tags': ['观叶植物', '常春藤'],
        'is_contacted': False,
    },

    
    {
        'user': 'garden_dad',
        'matched_user': 'expert_flower',
        'match_type': 'expert',
        'similarity_score': 0.89,
        'match_reason': '庭院种植月季和花卉，匹配花卉专家',
        'matched_tags': ['月季', '庭院种植', '开花植物'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '地栽月季的修剪和施肥方案非常实用',
    },
    {
        'user': 'garden_dad',
        'matched_user': 'herb_garden',
        'match_type': 'peer',
        'similarity_score': 0.76,
        'match_reason': '都种植罗勒和迷迭香等香草',
        'matched_tags': ['香草植物', '罗勒', '迷迭香'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '九层塔和罗勒品种鉴别的讨论很有意思',
    },
    {
        'user': 'garden_dad',
        'matched_user': 'balcony_garden',
        'match_type': 'peer',
        'similarity_score': 0.71,
        'match_reason': '都养月季和香草',
        'matched_tags': ['月季', '香草'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '分享了月季夏剪的经验',
    },

    
    {
        'user': 'tiny_garden',
        'matched_user': 'expert_succulent',
        'match_type': 'expert',
        'similarity_score': 0.75,
        'match_reason': '微型盆景和多肉景观有交集',
        'matched_tags': ['微型盆景', '多肉景观'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '薄雪万年草铺面的技巧学到了',
    },
    {
        'user': 'tiny_garden',
        'matched_user': 'fern_lover',
        'match_type': 'peer',
        'similarity_score': 0.72,
        'match_reason': '都在做板植和微型景观',
        'matched_tags': ['板植', '微景观'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '鹿角蕨微型板作品的创意给了我启发',
    },

    
    {
        'user': 'water_garden',
        'matched_user': 'expert_foliage',
        'match_type': 'expert',
        'similarity_score': 0.81,
        'match_reason': '水培植物养护匹配观叶植物专家',
        'matched_tags': ['水培', '观叶植物'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '白掌水培的营养液配比建议很好',
    },
    {
        'user': 'water_garden',
        'matched_user': 'tropical_fan',
        'match_type': 'peer',
        'similarity_score': 0.73,
        'match_reason': '都养白掌和合果芋，水培经验可交流',
        'matched_tags': ['白掌', '合果芋', '水培'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '合果芋水培转soil的经验很有帮助',
    },
    {
        'user': 'water_garden',
        'matched_user': 'office_plant',
        'match_type': 'peer',
        'similarity_score': 0.67,
        'match_reason': '都养白掌和室内观叶植物',
        'matched_tags': ['白掌', '室内'],
        'is_contacted': False,
    },

    
    {
        'user': 'night_grower',
        'matched_user': 'expert_foliage',
        'match_type': 'expert',
        'similarity_score': 0.79,
        'match_reason': '室内耐阴植物养护匹配观叶专家',
        'matched_tags': ['耐阴植物', '室内', '观叶植物'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '推荐了几款适合补光灯的功率，非常实用',
    },
    {
        'user': 'night_grower',
        'matched_user': 'office_plant',
        'match_type': 'peer',
        'similarity_score': 0.76,
        'match_reason': '都在室内低光环境养植物',
        'matched_tags': ['室内', '耐阴植物', '袖珍椰子'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '交流了补光灯使用的心得',
    },

    
    {
        'user': 'rooftop_girl',
        'matched_user': 'expert_flower',
        'match_type': 'expert',
        'similarity_score': 0.93,
        'match_reason': '天台花园的月季和绣球养护匹配花卉专家',
        'matched_tags': ['月季', '绣球', '天台花园', '开花植物'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '月季病虫害防治方案太专业了，照做效果很好',
    },
    {
        'user': 'rooftop_girl',
        'matched_user': 'flower_mama',
        'match_type': 'peer',
        'similarity_score': 0.82,
        'match_reason': '都养月季和绣球，养护品种高度重合',
        'matched_tags': ['月季', '绣球', '开花植物'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '绣球调色的经验互相分享，收获很大',
    },
    {
        'user': 'rooftop_girl',
        'matched_user': 'balcony_garden',
        'match_type': 'peer',
        'similarity_score': 0.77,
        'match_reason': '都在户外空间种花',
        'matched_tags': ['月季', '栀子', '户外'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '分享了天台防风的经验',
    },

    
    {
        'user': 'plant_doctor',
        'matched_user': 'expert_foliage',
        'match_type': 'expert',
        'similarity_score': 0.84,
        'match_reason': '诊断植物问题需要观叶植物专业知识',
        'matched_tags': ['橡皮树', '琴叶榕', '病虫害'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '琴叶榕介壳虫根除方案非常有效',
    },
    {
        'user': 'plant_doctor',
        'matched_user': 'expert_flower',
        'match_type': 'expert',
        'similarity_score': 0.80,
        'match_reason': '月季病害诊断需要花卉专家协助',
        'matched_tags': ['月季', '病虫害', '红蜘蛛'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '红蜘蛛的综合防治方案学到了',
    },
    {
        'user': 'plant_doctor',
        'matched_user': 'rooftop_girl',
        'match_type': 'peer',
        'similarity_score': 0.70,
        'match_reason': '都养月季，可交流病害防治经验',
        'matched_tags': ['月季', '病虫害'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '她的天台月季也遇到红蜘蛛，互相支招',
    },

    
    {
        'user': 'orchid_lover',
        'matched_user': 'expert_flower',
        'match_type': 'expert',
        'similarity_score': 0.86,
        'match_reason': '兰花养护匹配花卉专家',
        'matched_tags': ['兰花', '蝴蝶兰', '开花植物'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '蝴蝶兰催花的温差控制讲得非常到位',
    },
    {
        'user': 'orchid_lover',
        'matched_user': 'flower_mama',
        'match_type': 'peer',
        'similarity_score': 0.65,
        'match_reason': '都养开花植物',
        'matched_tags': ['开花植物'],
        'is_contacted': False,
    },
    {
        'user': 'orchid_lover',
        'matched_user': 'balcony_garden',
        'match_type': 'peer',
        'similarity_score': 0.62,
        'match_reason': '都对花期管理感兴趣',
        'matched_tags': ['花期管理'],
        'is_contacted': True,
        'feedback': 3,
        'feedback_comment': '养护方向差异比较大，收获一般',
    },

    
    {
        'user': 'herb_garden',
        'matched_user': 'expert_herbs',
        'match_type': 'expert',
        'similarity_score': 0.91,
        'match_reason': '香草种植经验丰富，匹配香草专家',
        'matched_tags': ['香草植物', '罗勒', '迷迭香'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '薄荷和罗勒的扦插方法讲得特别细致',
    },
    {
        'user': 'garden_dad',
        'matched_user': 'expert_herbs',
        'match_type': 'expert',
        'similarity_score': 0.83,
        'match_reason': '庭院种香草，匹配香草专家',
        'matched_tags': ['香草植物', '庭院'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '迷迭香越冬保护的建议太实用了',
    },
    {
        'user': 'balcony_garden',
        'matched_user': 'expert_herbs',
        'match_type': 'expert',
        'similarity_score': 0.79,
        'match_reason': '阳台种植香草和花卉',
        'matched_tags': ['香草植物', '阳台'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '阳台香草搭配种植方案很实用',
    },

    
    {
        'user': 'water_garden',
        'matched_user': 'expert_hydro',
        'match_type': 'expert',
        'similarity_score': 0.94,
        'match_reason': '水培爱好者匹配水培专家',
        'matched_tags': ['水培', '营养液', '水培植物'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '营养液EC值控制的方法太专业了',
    },
    {
        'user': 'tropical_fan',
        'matched_user': 'expert_hydro',
        'match_type': 'expert',
        'similarity_score': 0.77,
        'match_reason': '有水培植物经验',
        'matched_tags': ['水培', '合果芋'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '水培合果芋的根系处理学到了',
    },
    {
        'user': 'night_grower',
        'matched_user': 'expert_hydro',
        'match_type': 'expert',
        'similarity_score': 0.72,
        'match_reason': '室内植物养护可考虑水培方案',
        'matched_tags': ['室内', '水培'],
        'is_contacted': False,
    },

    
    {
        'user': 'tiny_garden',
        'matched_user': 'expert_bonsai',
        'match_type': 'expert',
        'similarity_score': 0.90,
        'match_reason': '微型盆景爱好者匹配盆景专家',
        'matched_tags': ['微型盆景', '盆景造型', '微景观'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '玉树老桩造型的技法讲解太好了',
    },
    {
        'user': 'fern_lover',
        'matched_user': 'expert_bonsai',
        'match_type': 'expert',
        'similarity_score': 0.74,
        'match_reason': '板植和景观制作有交集',
        'matched_tags': ['板植', '景观'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '鹿角蕨板植框架的设计思路受益匪浅',
    },
    {
        'user': 'cactus_king',
        'matched_user': 'expert_bonsai',
        'match_type': 'expert',
        'similarity_score': 0.70,
        'match_reason': '多肉造景和盆景有相通之处',
        'matched_tags': ['造景', '盆景'],
        'is_contacted': False,
    },

    
    {
        'user': 'plant_doctor',
        'matched_user': 'expert_pest',
        'match_type': 'expert',
        'similarity_score': 0.95,
        'match_reason': '植物诊断爱好者匹配病虫害专家',
        'matched_tags': ['病虫害', '植物诊断', '红蜘蛛', '介壳虫'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '系统性的综合防治方案让我大开眼见，比以前零散摸索强太多了',
    },
    {
        'user': 'rooftop_girl',
        'matched_user': 'expert_pest',
        'match_type': 'expert',
        'similarity_score': 0.85,
        'match_reason': '天台月季病虫害频发',
        'matched_tags': ['月季', '病虫害', '蚜虫'],
        'is_contacted': True,
        'feedback': 5,
        'feedback_comment': '轮换用药方案终于把红蜘蛛控制住了',
    },
    {
        'user': 'flower_mama',
        'matched_user': 'expert_pest',
        'match_type': 'expert',
        'similarity_score': 0.78,
        'match_reason': '月季白粉病问题',
        'matched_tags': ['月季', '白粉病'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '白粉病的预防方案有用',
    },
    {
        'user': 'green_thumb',
        'matched_user': 'expert_pest',
        'match_type': 'expert',
        'similarity_score': 0.73,
        'match_reason': '室内植物也有虫害困扰',
        'matched_tags': ['室内', '病虫害'],
        'is_contacted': True,
        'feedback': 4,
        'feedback_comment': '有机防治方案比化学农药安全多了',
    },
]

MATCH_REQUEST_SEEDS = [
    {
        'from_user': 'plant_lover1',
        'to_user': 'expert_succulent',
        'message': '您好，我是多肉新手，最近熊童子出现黑腐迹象，想请教一下怎么处理。',
        'status': 'accepted',
    },
    {
        'from_user': 'office_plant',
        'to_user': 'expert_foliage',
        'message': '专家您好，我在办公室北向窗养了白掌和袖珍椰子，想请教耐阴植物的养护技巧。',
        'status': 'accepted',
    },
    {
        'from_user': 'flower_mama',
        'to_user': 'expert_flower',
        'message': '老师好，我想了解绣球调色的具体操作方法，我调了一个月还是粉色。',
        'status': 'accepted',
    },
    {
        'from_user': 'fern_lover',
        'to_user': 'expert_foliage',
        'message': '想请教蕨类板植的湿度控制和浇水节奏。',
        'status': 'accepted',
    },
    {
        'from_user': 'cactus_king',
        'to_user': 'expert_succulent',
        'message': '想咨询仙人掌冬季管理的注意事项，特别是北方有暖气的情况。',
        'status': 'accepted',
    },
    {
        'from_user': 'herb_garden',
        'to_user': 'balcony_garden',
        'message': '看到你也在阳台种香草，咱们可以交流一下种植经验吗？',
        'status': 'accepted',
    },
    {
        'from_user': 'weekend_gardener',
        'to_user': 'succulent_fan',
        'message': '你收集了那么多多肉品种，有没有多余的小崽可以分享？',
        'status': 'accepted',
    },
    {
        'from_user': 'green_thumb',
        'to_user': 'fern_lover',
        'message': '看你家鹿角蕨养得真好，能不能分享一下上板的经验？',
        'status': 'accepted',
    },
    {
        'from_user': 'flower_mama',
        'to_user': 'balcony_garden',
        'message': '我也在阳台种了月季和绣球，想交流一下养护心得。',
        'status': 'accepted',
    },
    {
        'from_user': 'plant_lover1',
        'to_user': 'green_thumb',
        'message': '我也想养观叶植物，能推荐几个好养的品种吗？',
        'status': 'pending',
    },
    {
        'from_user': 'cactus_king',
        'to_user': 'weekend_gardener',
        'message': '看你的多肉收藏不错，有兴趣交换一些品种吗？',
        'status': 'pending',
    },

    
    {
        'from_user': 'tropical_fan',
        'to_user': 'expert_foliage',
        'message': '想请教合果芋攀爬柱的制作方法和水苔绑扎技巧。',
        'status': 'accepted',
    },
    {
        'from_user': 'tropical_fan',
        'to_user': 'fern_lover',
        'message': '您好，看到你的鹿角蕨板植作品太棒了，能交流一下吗？',
        'status': 'accepted',
    },
    {
        'from_user': 'garden_dad',
        'to_user': 'expert_flower',
        'message': '家里院子的月季最近总是黑斑病，想请教系统的防治方案。',
        'status': 'accepted',
    },
    {
        'from_user': 'garden_dad',
        'to_user': 'herb_garden',
        'message': '你也种罗勒？我种了好几种九层塔，可以交流一下品种和用法。',
        'status': 'accepted',
    },
    {
        'from_user': 'tiny_garden',
        'to_user': 'expert_succulent',
        'message': '请教一下多肉微景观的搭配和养护要点。',
        'status': 'accepted',
    },
    {
        'from_user': 'tiny_garden',
        'to_user': 'fern_lover',
        'message': '想学习微型鹿角蕨板植的做法，您方便指导吗？',
        'status': 'accepted',
    },
    {
        'from_user': 'water_garden',
        'to_user': 'expert_foliage',
        'message': '水培白掌最近根系发黑，想请教一下原因和处理方法。',
        'status': 'accepted',
    },
    {
        'from_user': 'water_garden',
        'to_user': 'tropical_fan',
        'message': '你的合果芋是水培还是土培？我想试试水培。',
        'status': 'accepted',
    },
    {
        'from_user': 'night_grower',
        'to_user': 'expert_foliage',
        'message': '夜班族，植物经常缺光，想请教补光灯的选择和使用。',
        'status': 'accepted',
    },
    {
        'from_user': 'night_grower',
        'to_user': 'office_plant',
        'message': '你办公室的植物是怎么解决光照问题的？可以交流一下吗？',
        'status': 'accepted',
    },
    {
        'from_user': 'rooftop_girl',
        'to_user': 'expert_flower',
        'message': '天台月季红蜘蛛反复发作，想请教根治方案。',
        'status': 'accepted',
    },
    {
        'from_user': 'rooftop_girl',
        'to_user': 'flower_mama',
        'message': '看你的绣球调色效果太好了，能分享一下经验吗？',
        'status': 'accepted',
    },
    {
        'from_user': 'plant_doctor',
        'to_user': 'expert_foliage',
        'message': '请教琴叶榕介壳虫的根除方案，酒精擦除治标不治本。',
        'status': 'accepted',
    },
    {
        'from_user': 'plant_doctor',
        'to_user': 'expert_flower',
        'message': '想了解月季红蜘蛛的综合防治策略，正在做对比实验。',
        'status': 'accepted',
    },
    {
        'from_user': 'orchid_lover',
        'to_user': 'expert_flower',
        'message': '蝴蝶兰花谢后一直不复花，已经两年了，怎么催花？',
        'status': 'accepted',
    },
    {
        'from_user': 'orchid_lover',
        'to_user': 'balcony_garden',
        'message': '你有没有养过兰花?想交流一下花期管理的经验。',
        'status': 'accepted',
    },
    {
        'from_user': 'rooftop_girl',
        'to_user': 'balcony_garden',
        'message': '你阳台的栀子花养得真好，我天台的栀子叶子总发黄。',
        'status': 'pending',
    },
    {
        'from_user': 'plant_doctor',
        'to_user': 'rooftop_girl',
        'message': '你天台的月季是不是也有红蜘蛛?我在研究不同防治方案的效果。',
        'status': 'pending',
    },
    {
        'from_user': 'water_garden',
        'to_user': 'night_grower',
        'message': '你的白掌是土培吧？我水培的白掌效果不错，要不要试试？',
        'status': 'pending',
    },

    
    {
        'from_user': 'herb_garden',
        'to_user': 'expert_herbs',
        'message': '听说您是香草种植专家，我的薄荷总是徒长茎秆很细怎么办？',
        'status': 'accepted',
    },
    {
        'from_user': 'garden_dad',
        'to_user': 'expert_herbs',
        'message': '我院子里的迷迭香冬天总冻死，北方怎么越冬？',
        'status': 'accepted',
    },
    {
        'from_user': 'balcony_garden',
        'to_user': 'expert_herbs',
        'message': '阳台空间有限，香草和花卉怎么搭配种植？',
        'status': 'accepted',
    },
    {
        'from_user': 'water_garden',
        'to_user': 'expert_hydro',
        'message': '想系统学习水培营养液配比，EC值和pH应该控制在什么范围？',
        'status': 'accepted',
    },
    {
        'from_user': 'tropical_fan',
        'to_user': 'expert_hydro',
        'message': '想把合果芋从土培转水培，根系处理有什么技巧？',
        'status': 'accepted',
    },
    {
        'from_user': 'tiny_garden',
        'to_user': 'expert_bonsai',
        'message': '我想学习玉树老桩造型，有什么入门建议？',
        'status': 'accepted',
    },
    {
        'from_user': 'fern_lover',
        'to_user': 'expert_bonsai',
        'message': '想做大型鹿角蕨板植作品，板材和水苔架构怎么设计？',
        'status': 'accepted',
    },
    {
        'from_user': 'plant_doctor',
        'to_user': 'expert_pest',
        'message': '我对综合防治方案很感兴趣，能系统讲讲轮换用药的策略吗？',
        'status': 'accepted',
    },
    {
        'from_user': 'rooftop_girl',
        'to_user': 'expert_pest',
        'message': '天台月季红蜘蛛反复爆发，化学药剂也控制不住，有没有更好的方案？',
        'status': 'accepted',
    },
    {
        'from_user': 'flower_mama',
        'to_user': 'expert_pest',
        'message': '月季白粉病每年春天都犯，怎么预防？',
        'status': 'accepted',
    },
    {
        'from_user': 'green_thumb',
        'to_user': 'expert_pest',
        'message': '家里有小孩，室内植物有虫不敢用农药，有没有安全的方法？',
        'status': 'accepted',
    },
    {
        'from_user': 'night_grower',
        'to_user': 'expert_hydro',
        'message': '室内光线很差，水培会不会比土培好管理一些？',
        'status': 'pending',
    },
    {
        'from_user': 'cactus_king',
        'to_user': 'expert_bonsai',
        'message': '多肉能不能做成盆景风格？有没有好的造型方案？',
        'status': 'pending',
    },
]

TAG_WEIGHT_SEEDS = [
    {'tag_type': 'plant_type', 'weight': 1.5, 'description': '植物类型偏好，权重最高'},
    {'tag_type': 'care_environment', 'weight': 1.2, 'description': '养护环境匹配'},
    {'tag_type': 'interest', 'weight': 1.0, 'description': '兴趣方向匹配'},
    {'tag_type': 'problem', 'weight': 0.8, 'description': '问题类型匹配'},
]

__all__ = ['MATCH_RECORD_SEEDS', 'MATCH_REQUEST_SEEDS', 'TAG_WEIGHT_SEEDS']
