# Generated by Django 4.2.27 on 2026-04-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_notificationpreference"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usertag",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "用户标签",
                "verbose_name_plural": "用户标签",
            },
        ),
    ]
