CATEGORY_DEFS = [
    {'name': '多肉植物', 'description': '肉质茎叶植物，耐旱且适合家庭栽培', 'order': 1},
    {'name': '观叶植物', 'description': '以叶片观赏为主的室内植物', 'order': 2},
    {'name': '开花植物', 'description': '以花朵观赏为主的植物', 'order': 3},
    {'name': '藤蔓植物', 'description': '适合攀援或垂吊养护的植物', 'order': 4},
    {'name': '水培植物', 'description': '适合水培或半水培环境的植物', 'order': 5},
    {'name': '香草植物', 'description': '兼具香气与食用价值的草本植物', 'order': 6},
    {'name': '仙人掌', 'description': '仙人掌科及近似耐旱观赏植物', 'order': 7},
    {'name': '蕨类植物', 'description': '偏爱高湿与散射光环境的观赏蕨类', 'order': 8},
]

TAG_DEFS = {
    '新手友好': '#4CAF50',
    '耐旱': '#FF9800',
    '喜阴': '#607D8B',
    '喜光': '#FFEB3B',
    '净化空气': '#00BCD4',
    '观花': '#E91E63',
    '观叶': '#8BC34A',
    '香气': '#FF5722',
    '可食用': '#795548',
    '耐寒': '#2196F3',
    '室内友好': '#26A69A',
    '垂吊': '#AB47BC',
    '水培': '#42A5F5',
    '攀援': '#5C6BC0',
    '高湿': '#009688',
    '驱蚊': '#7CB342',
}

PLANT_CATALOG = [
    {
        'name': '白掌',
        'scientific_name': 'Spathiphyllum wallisii',
        'alias': '白鹤芋、一帆风顺',
        'wiki_title': '白鶴芋',
        'category': '观叶植物',
        'summary': '白掌又名白鹤芋、一帆风顺，为天南星科多年生常绿草本，原产中南美洲热带雨林，叶片翠绿、佛焰苞洁白，兼具观花与观叶价值，也常用于室内盆栽和水培观赏。',
        'difficulty': 'easy',
        'light_requirement': 'indirect',
        'water_requirement': 'medium',
        'temperature_min': 12,
        'temperature_max': 30,
        'humidity': '喜欢温暖湿润环境，空气湿度50%-75%更稳定。',
        'soil_requirement': '疏松透气的腐殖土，保持排水和保水的平衡。',
        'fertilizer_tips': '生长期每2到3周施一次稀薄液肥，花期前可增加磷钾肥。',
        'pruning_tips': '及时剪掉残花和黄叶，维持株型整洁。',
        'propagation': '可通过分株繁殖。',
        'common_problems': '叶片下垂多为缺水，叶尖发黄常与低湿或肥害有关。',
        'care_tips': '避免暴晒，土壤微湿即可，夏季可适当喷水增湿。',
        'tags': ['新手友好', '观花', '观叶', '净化空气', '室内友好'],
    },
    {
        'name': '红掌',
        'scientific_name': 'Anthurium andraeanum',
        'alias': '花烛、火鹤花',
        'wiki_title': '花燭',
        'category': '开花植物',
        'summary': '红掌又名花烛、火鹤花，为天南星科多年生草本，原产热带美洲雨林，佛焰苞鲜亮、肉穗花序直立，花期长，适合盆栽、切花和室内观赏。',
        'difficulty': 'medium',
        'light_requirement': 'indirect',
        'water_requirement': 'medium',
        'temperature_min': 15,
        'temperature_max': 32,
        'humidity': '喜欢高湿环境，湿度60%-80%表现最好。',
        'soil_requirement': '宜用疏松透气、富含有机质的基质。',
        'fertilizer_tips': '生长期每2周补一次薄肥，花期重视磷钾元素。',
        'pruning_tips': '花败后及时从花梗基部剪除。',
        'propagation': '分株繁殖为主。',
        'common_problems': '不开花多因光线不足，叶片焦边常与空气干燥相关。',
        'care_tips': '适合明亮散射光环境，避免冷风和强光直射。',
        'tags': ['观花', '室内友好', '高湿'],
    },
    {
        'name': '文竹',
        'scientific_name': 'Asparagus setaceus',
        'alias': '云片松、云竹',
        'wiki_title': '文竹',
        'category': '观叶植物',
        'summary': '文竹属天门冬科天门冬属，原产非洲南部，枝叶纤细秀丽、姿态轻盈文雅，是常见的室内观叶盆栽，也常作为小型盆景和插花陪衬材料。',
        'difficulty': 'medium',
        'light_requirement': 'indirect',
        'water_requirement': 'medium',
        'temperature_min': 10,
        'temperature_max': 28,
        'humidity': '喜湿润，空气湿度50%-70%较适宜。',
        'soil_requirement': '偏疏松的腐叶土或泥炭土基质。',
        'fertilizer_tips': '生长期每月施一次稀薄液肥即可。',
        'pruning_tips': '及时修去黄枝、徒长枝，保持通风。',
        'propagation': '可播种或分株繁殖。',
        'common_problems': '黄叶常与干燥、暴晒或积水有关。',
        'care_tips': '放在通风良好的明亮处，避免反复移动位置。',
        'tags': ['观叶', '喜阴', '室内友好'],
    },
    {
        'name': '富贵竹',
        'scientific_name': 'Dracaena sanderiana',
        'alias': '开运竹、万年竹',
        'wiki_title': '富貴竹',
        'category': '水培植物',
        'summary': '富贵竹又名开运竹、万年竹，为龙血树属常绿观叶植物，原产非洲，茎节似竹而非真正竹类，叶色翠绿，常用于室内盆栽和水培造型，寓意富贵平安。',
        'difficulty': 'easy',
        'light_requirement': 'indirect',
        'water_requirement': 'high',
        'temperature_min': 12,
        'temperature_max': 30,
        'humidity': '普通室内湿度即可，保持水质清洁更重要。',
        'soil_requirement': '可水培，也可用疏松土壤盆栽。',
        'fertilizer_tips': '水培时少量营养液即可，过量易烧根。',
        'pruning_tips': '顶部过高时可截短重新扦插。',
        'propagation': '茎段扦插成活率高。',
        'common_problems': '黄叶多与水质差、温度低或强光照射有关。',
        'care_tips': '水培需勤换水，避免长期阳光暴晒。',
        'tags': ['新手友好', '水培', '室内友好', '观叶'],
    },
    {
        'name': '铜钱草',
        'scientific_name': 'Hydrocotyle verticillata',
        'alias': '香菇草',
        'wiki_title': '天胡荽',
        'category': '水培植物',
        'summary': '铜钱草通常指天胡荽属观赏植物，叶片圆润如钱币，茎匍匐生长，适合水培、半水培和浅盆栽培，是常见的小型桌面观叶植物。',
        'difficulty': 'easy',
        'light_requirement': 'partial_sun',
        'water_requirement': 'high',
        'temperature_min': 8,
        'temperature_max': 32,
        'humidity': '喜湿环境，基质不能长期干透。',
        'soil_requirement': '适合水培、浅水盆栽或保水性较强的混合土。',
        'fertilizer_tips': '生长期少量多次补肥即可。',
        'pruning_tips': '定期修剪老叶和过密叶柄。',
        'propagation': '分株和匍匐茎繁殖都很容易。',
        'common_problems': '叶片变小或发黄通常与缺光、缺肥有关。',
        'care_tips': '给予充足散射光或柔和日照，保持水分稳定。',
        'tags': ['新手友好', '水培', '喜光', '观叶'],
    },
    {
        'name': '罗勒',
        'scientific_name': 'Ocimum basilicum',
        'alias': '九层塔',
        'wiki_title': '羅勒',
        'category': '香草植物',
        'summary': '罗勒又名九层塔、金不换，为唇形科一年生或短命多年生香草植物，叶、茎和花序含芳香油，常用于烹饪调味、香草茶和家庭阳台种植。',
        'difficulty': 'easy',
        'light_requirement': 'full_sun',
        'water_requirement': 'medium',
        'temperature_min': 12,
        'temperature_max': 35,
        'humidity': '温暖通风环境最适宜，避免长期闷湿。',
        'soil_requirement': '肥沃疏松、排水良好的栽培土。',
        'fertilizer_tips': '生长期每2周补充一次薄肥。',
        'pruning_tips': '常摘心和采叶有助于分枝。',
        'propagation': '播种和扦插均可。',
        'common_problems': '徒长多因缺光，烂根多因积水和闷热。',
        'care_tips': '保持充足光照，及时摘除花序可延长采收期。',
        'tags': ['可食用', '香气', '喜光', '新手友好'],
    },
    {
        'name': '迷迭香',
        'scientific_name': 'Salvia rosmarinus',
        'alias': '罗斯玛丽',
        'wiki_title': '迷迭香',
        'category': '香草植物',
        'summary': '迷迭香为唇形科常绿亚灌木，原产地中海沿岸，枝叶狭长并带浓郁芳香，可作香草调料、观赏植物和芳香植物，喜光、耐旱但不耐涝。',
        'difficulty': 'medium',
        'light_requirement': 'full_sun',
        'water_requirement': 'low',
        'temperature_min': 5,
        'temperature_max': 32,
        'humidity': '偏干燥通风的环境更适合生长。',
        'soil_requirement': '排水良好的砂质土壤。',
        'fertilizer_tips': '薄肥即可，忌浓肥。',
        'pruning_tips': '花后或生长旺季轻剪，促进侧枝萌发。',
        'propagation': '可扦插繁殖。',
        'common_problems': '黄叶多与积水和通风差有关。',
        'care_tips': '尽量放在光照充足的位置，浇水遵循见干见湿。',
        'tags': ['香气', '可食用', '喜光', '耐旱', '驱蚊'],
    },
    {
        'name': '茉莉',
        'scientific_name': 'Jasminum sambac',
        'alias': '茉莉花',
        'wiki_title': '茉莉花',
        'category': '开花植物',
        'summary': '茉莉花为木犀科素馨属灌木，原产印度及周边热带地区，花朵洁白芬芳，常用于观赏、窨制花茶以及提取香精，是中国南方常见香花植物。',
        'difficulty': 'medium',
        'light_requirement': 'full_sun',
        'water_requirement': 'medium',
        'temperature_min': 8,
        'temperature_max': 34,
        'humidity': '温暖湿润并保持通风更利于开花。',
        'soil_requirement': '微酸性、肥沃透气的栽培土。',
        'fertilizer_tips': '花前增施磷钾肥，生长期薄肥勤施。',
        'pruning_tips': '花后及时短截，促进新枝和二次开花。',
        'propagation': '扦插繁殖较常见。',
        'common_problems': '不开花常因缺光或枝条过老。',
        'care_tips': '日照越足花越香，花期注意补肥和通风。',
        'tags': ['观花', '香气', '喜光'],
    },
    {
        'name': '栀子花',
        'scientific_name': 'Gardenia jasminoides',
        'alias': '栀子',
        'wiki_title': '梔子',
        'category': '开花植物',
        'summary': '栀子花为茜草科栀子属常绿灌木，花色洁白、香气清雅，是典型的香花植物之一，兼具庭院观赏、盆栽应用以及花果利用价值。',
        'difficulty': 'hard',
        'light_requirement': 'partial_sun',
        'water_requirement': 'medium',
        'temperature_min': 10,
        'temperature_max': 32,
        'humidity': '喜湿润和通风的环境。',
        'soil_requirement': '偏酸性、透气保水的培养土。',
        'fertilizer_tips': '生长期补充酸性肥和磷钾肥。',
        'pruning_tips': '花后修剪残花和过密枝。',
        'propagation': '扦插和压条繁殖均可。',
        'common_problems': '黄叶常与缺铁、碱化或浇水不当有关。',
        'care_tips': '养护重点在于酸性环境、通风与稳定光照。',
        'tags': ['观花', '香气'],
    },
    {
        'name': '蝴蝶兰',
        'scientific_name': 'Phalaenopsis spp.',
        'alias': '蝶兰',
        'wiki_title': '蝴蝶蘭',
        'category': '开花植物',
        'summary': '蝴蝶兰属兰科附生性植物，多生于热带和亚热带雨林树干上，花形似蝶、花期较长，因观赏价值高而被誉为“洋兰王后”，常见于年宵花和室内盆栽。',
        'difficulty': 'medium',
        'light_requirement': 'indirect',
        'water_requirement': 'medium',
        'temperature_min': 15,
        'temperature_max': 30,
        'humidity': '喜欢空气湿度60%以上的环境。',
        'soil_requirement': '常用树皮、水苔等透气基质栽培。',
        'fertilizer_tips': '薄肥勤施，花期适度减少施肥。',
        'pruning_tips': '花谢后可根据花梗状态决定短截位置。',
        'propagation': '组培为主，家庭中偶见高芽繁殖。',
        'common_problems': '烂根常与积水和闷湿有关。',
        'care_tips': '重点是通风、散射光和根系透气。',
        'tags': ['观花', '高湿', '室内友好'],
    },
    {
        'name': '君子兰',
        'scientific_name': 'Clivia miniata',
        'alias': '大花君子兰',
        'wiki_title': '君子蘭',
        'category': '开花植物',
        'summary': '君子兰为石蒜科多年生常绿草本，原产非洲南部亚热带森林，叶片厚实整齐、花序端庄，适合温室和室内盆栽观赏，喜半阴凉爽环境。',
        'difficulty': 'medium',
        'light_requirement': 'indirect',
        'water_requirement': 'low',
        'temperature_min': 8,
        'temperature_max': 28,
        'humidity': '普通室内湿度即可，忌盆土长期潮湿。',
        'soil_requirement': '疏松肥沃且排水良好的腐殖土。',
        'fertilizer_tips': '生长期薄肥勤施，孕蕾期补磷钾。',
        'pruning_tips': '及时去除残花和老叶。',
        'propagation': '分株繁殖较常见。',
        'common_problems': '夹箭、不开花通常与温差不足或养分失衡有关。',
        'care_tips': '重视秋冬养护节奏和昼夜温差。',
        'tags': ['观花', '室内友好'],
    },
    {
        'name': '月季',
        'scientific_name': 'Rosa chinensis',
        'alias': '月月红',
        'wiki_title': '月季',
        'category': '开花植物',
        'summary': '月季为蔷薇科蔷薇属观赏灌木，花色与花型丰富、开花周期长，是庭院、阳台和城市绿化中最常见的观花植物之一。',
        'difficulty': 'medium',
        'light_requirement': 'full_sun',
        'water_requirement': 'medium',
        'temperature_min': -10,
        'temperature_max': 35,
        'humidity': '通风良好比高湿更重要。',
        'soil_requirement': '疏松肥沃、排水良好的微酸性土壤。',
        'fertilizer_tips': '花前花后及时追肥，重视有机肥和磷钾肥。',
        'pruning_tips': '花后回剪和冬季修剪都很关键。',
        'propagation': '扦插和嫁接均可。',
        'common_problems': '白粉病、黑斑病和虫害是常见难题。',
        'care_tips': '想开好花必须保证日照、通风和持续补肥。',
        'tags': ['观花', '喜光', '耐寒'],
    },
    {
        'name': '绣球',
        'scientific_name': 'Hydrangea macrophylla',
        'alias': '八仙花',
        'wiki_title': '繡球花',
        'category': '开花植物',
        'summary': '绣球又名八仙花、紫阳花，为绣球花科落叶灌木，伞房状花序近球形，花量大且花色会受土壤酸碱度影响，是经典的园艺观赏花木。',
        'difficulty': 'medium',
        'light_requirement': 'partial_sun',
        'water_requirement': 'high',
        'temperature_min': -5,
        'temperature_max': 30,
        'humidity': '喜湿润，炎热季节尤其不能缺水。',
        'soil_requirement': '肥沃疏松并具有一定保水性的土壤。',
        'fertilizer_tips': '春季和花前补肥，注意控制氮肥比例。',
        'pruning_tips': '修剪需结合品种和花芽着生习性。',
        'propagation': '扦插繁殖较常见。',
        'common_problems': '焦边、萎蔫常与暴晒或缺水有关。',
        'care_tips': '夏季半阴最稳妥，保持水分和通风很关键。',
        'tags': ['观花', '高湿'],
    },
    {
        'name': '橡皮树',
        'scientific_name': 'Ficus elastica',
        'alias': '印度榕',
        'wiki_title': '印度橡膠榕',
        'category': '观叶植物',
        'summary': '橡皮树又名印度榕，为桑科榕属常绿乔木，叶片厚革质且富有光泽，含白色乳汁，既可作盆栽观叶植物，也常用于室内空间绿化布置。',
        'difficulty': 'easy',
        'light_requirement': 'indirect',
        'water_requirement': 'low',
        'temperature_min': 10,
        'temperature_max': 32,
        'humidity': '普通室内环境即可。',
        'soil_requirement': '疏松透气、排水良好的培养土。',
        'fertilizer_tips': '生长期每月施一次复合肥。',
        'pruning_tips': '春季可打顶促发侧枝。',
        'propagation': '扦插和高压繁殖均可。',
        'common_problems': '掉叶常与低温、缺光或浇水不当有关。',
        'care_tips': '适当控水并保持明亮散射光，叶片会更有光泽。',
        'tags': ['观叶', '室内友好', '净化空气'],
    },
    {
        'name': '琴叶榕',
        'scientific_name': 'Ficus lyrata',
        'alias': '琴叶橡皮树',
        'wiki_title': '琴葉榕',
        'category': '观叶植物',
        'summary': '琴叶榕为桑科榕属木本植物，因叶片形似提琴而得名，株形挺拔、叶片厚大，常作为现代家居与商业空间中的大型观叶植物。',
        'difficulty': 'medium',
        'light_requirement': 'indirect',
        'water_requirement': 'low',
        'temperature_min': 12,
        'temperature_max': 30,
        'humidity': '喜欢稳定环境，湿度40%-70%较适宜。',
        'soil_requirement': '透气排水良好的营养土。',
        'fertilizer_tips': '春夏每月补一次均衡肥。',
        'pruning_tips': '打顶可控制高度并促进分枝。',
        'propagation': '扦插和高压繁殖。',
        'common_problems': '黑斑和落叶常与浇水过多及环境变化大有关。',
        'care_tips': '不宜频繁挪动位置，养护节奏要稳定。',
        'tags': ['观叶', '室内友好'],
    },
    {
        'name': '豆瓣绿',
        'scientific_name': 'Peperomia obtusifolia',
        'alias': '圆叶椒草',
        'wiki_title': '椒草',
        'category': '观叶植物',
        'summary': '豆瓣绿为胡椒科多年生常绿草本，植株小巧、茎叶肉质、叶色浓绿有光泽，常作为桌面和书架上的小型盆栽观叶植物。',
        'difficulty': 'easy',
        'light_requirement': 'indirect',
        'water_requirement': 'low',
        'temperature_min': 12,
        'temperature_max': 30,
        'humidity': '适应普通室内湿度。',
        'soil_requirement': '疏松透气的颗粒型营养土。',
        'fertilizer_tips': '薄肥勤施即可，避免浓肥。',
        'pruning_tips': '可摘心促使株型更丰满。',
        'propagation': '叶插和枝插都较容易。',
        'common_problems': '烂根常由浇水过勤造成。',
        'care_tips': '宁可略干也不要过湿，适合新手练手。',
        'tags': ['新手友好', '观叶', '室内友好'],
    },
    {
        'name': '常春藤',
        'scientific_name': 'Hedera helix',
        'alias': '洋常春藤',
        'wiki_title': '常春藤',
        'category': '藤蔓植物',
        'summary': '常春藤为五加科常绿攀援植物，枝蔓柔韧、叶形变化丰富，既可垂吊也可攀附支架生长，是经典的室内外立体绿化植物。',
        'difficulty': 'easy',
        'light_requirement': 'indirect',
        'water_requirement': 'medium',
        'temperature_min': 5,
        'temperature_max': 28,
        'humidity': '喜较高空气湿度，但也需良好通风。',
        'soil_requirement': '疏松透气的腐殖土更利于生长。',
        'fertilizer_tips': '生长期每月施一次薄肥。',
        'pruning_tips': '常修剪可促进分枝和更密的垂吊效果。',
        'propagation': '枝条扦插极易成活。',
        'common_problems': '红蜘蛛和叶片干尖多与闷热干燥有关。',
        'care_tips': '适合明亮散射光环境，夏季注意降温通风。',
        'tags': ['攀援', '垂吊', '净化空气', '观叶'],
    },
    {
        'name': '合果芋',
        'scientific_name': 'Syngonium podophyllum',
        'alias': '箭叶芋',
        'wiki_title': '合果芋',
        'category': '藤蔓植物',
        'summary': '合果芋为天南星科多年生蔓性常绿草本，茎节具气生根，幼叶多呈箭形，成熟后叶形可分裂变化，常用于垂吊、立柱和室内热带造景。',
        'difficulty': 'easy',
        'light_requirement': 'indirect',
        'water_requirement': 'medium',
        'temperature_min': 12,
        'temperature_max': 30,
        'humidity': '喜欢湿润环境，湿度50%以上更佳。',
        'soil_requirement': '疏松肥沃的基质，保持透气。',
        'fertilizer_tips': '春夏每月施1到2次薄肥。',
        'pruning_tips': '适当修剪长蔓，促进株型丰满。',
        'propagation': '茎段扦插容易生根。',
        'common_problems': '叶色发淡通常与缺光或缺肥有关。',
        'care_tips': '适合明亮室内环境，可搭配支柱引导攀爬。',
        'tags': ['攀援', '垂吊', '观叶', '室内友好'],
    },
    {
        'name': '爱之蔓',
        'scientific_name': 'Ceropegia woodii',
        'alias': '心叶吊灯花',
        'wiki_title': '愛之蔓',
        'category': '藤蔓植物',
        'summary': '爱之蔓为萝藦科吊灯花属多年生多肉植物，原产南非，叶片呈心形、藤蔓细长下垂，根部具块茎，耐旱性强，是人气很高的垂吊型多肉。',
        'difficulty': 'easy',
        'light_requirement': 'indirect',
        'water_requirement': 'low',
        'temperature_min': 10,
        'temperature_max': 30,
        'humidity': '偏干燥环境更稳妥。',
        'soil_requirement': '排水透气好的多肉颗粒土。',
        'fertilizer_tips': '生长期少量补肥即可。',
        'pruning_tips': '藤蔓过长时可回剪并再扦插。',
        'propagation': '扦插和珠芽繁殖都较容易。',
        'common_problems': '黑腐和徒长常因积水、缺光造成。',
        'care_tips': '保持光线明亮和盆土偏干，可长得更紧凑。',
        'tags': ['垂吊', '耐旱', '观叶'],
    },
    {
        'name': '吊竹梅',
        'scientific_name': 'Tradescantia zebrina',
        'alias': '紫露草',
        'wiki_title': '吊竹梅',
        'category': '藤蔓植物',
        'summary': '吊竹梅为鸭跖草科多年生常绿蔓生草本，原产墨西哥，叶面具银白与紫绿色条纹，茎蔓匍匐或悬垂，生命力强，适合吊盆和地被栽培。',
        'difficulty': 'easy',
        'light_requirement': 'indirect',
        'water_requirement': 'medium',
        'temperature_min': 10,
        'temperature_max': 32,
        'humidity': '普通室内湿度即可。',
        'soil_requirement': '疏松排水的常规栽培土。',
        'fertilizer_tips': '生长期每月施一次薄肥。',
        'pruning_tips': '多摘心可促进爆盆。',
        'propagation': '枝条扦插极易成活。',
        'common_problems': '茎节拉长多因光照不足。',
        'care_tips': '光线明亮时叶色更鲜艳，但要避免正午暴晒。',
        'tags': ['垂吊', '观叶', '新手友好'],
    },
    {
        'name': '鹿角蕨',
        'scientific_name': 'Platycerium bifurcatum',
        'alias': '麋角羊齿',
        'wiki_title': '鹿角蕨',
        'category': '蕨类植物',
        'summary': '鹿角蕨为附生性观赏蕨类，原产热带和亚热带地区，具有贴附基质的营养叶与分叉如鹿角的孢子叶两种叶型，是板植和立体绿化中的代表性蕨类植物。',
        'difficulty': 'medium',
        'light_requirement': 'indirect',
        'water_requirement': 'medium',
        'temperature_min': 12,
        'temperature_max': 30,
        'humidity': '偏爱高湿和空气流通的环境。',
        'soil_requirement': '常附生在板材、水苔或树皮基质上。',
        'fertilizer_tips': '生长期低浓度补肥即可。',
        'pruning_tips': '一般不修剪功能叶，保持基质清洁即可。',
        'propagation': '分株繁殖为主。',
        'common_problems': '叶片干尖和生长停滞常与湿度不足有关。',
        'care_tips': '重视空气湿度和通风，不宜暴晒。',
        'tags': ['高湿', '观叶', '喜阴'],
    },
    {
        'name': '袖珍椰子',
        'scientific_name': 'Chamaedorea elegans',
        'alias': '客厅椰子',
        'wiki_title': '袖珍椰子',
        'category': '观叶植物',
        'summary': '袖珍椰子为棕榈科竹节椰属常绿小灌木，原产墨西哥和中美洲，株型小巧秀雅、叶片羽状开展，耐阴性较好，是常见的室内小型棕榈观叶植物。',
        'difficulty': 'easy',
        'light_requirement': 'shade',
        'water_requirement': 'medium',
        'temperature_min': 10,
        'temperature_max': 30,
        'humidity': '喜欢温暖湿润环境，注意空气流通。',
        'soil_requirement': '疏松透气、含腐殖质的培养土。',
        'fertilizer_tips': '生长期每月施一次薄肥。',
        'pruning_tips': '剪掉老黄叶即可。',
        'propagation': '播种为主，家庭中以购买成株为主。',
        'common_problems': '干尖常与空气干燥或强光有关。',
        'care_tips': '适合北向窗和办公环境，但不能长期积水。',
        'tags': ['喜阴', '室内友好', '观叶', '净化空气'],
    },
    {
        'name': '芦荟',
        'scientific_name': 'Aloe vera',
        'alias': '库拉索芦荟',
        'wiki_title': '蘆薈',
        'category': '多肉植物',
        'summary': '芦荟为芦荟属多年生多肉植物，原产非洲热带干旱地区，叶片肥厚多汁、边缘具细齿，既是常见的观赏盆栽，也因较高认知度而常被用于家庭栽培。',
        'difficulty': 'easy',
        'light_requirement': 'full_sun',
        'water_requirement': 'low',
        'temperature_min': 5,
        'temperature_max': 35,
        'humidity': '偏干燥环境更适合。',
        'soil_requirement': '适合颗粒较多、排水快的多肉土。',
        'fertilizer_tips': '生长期少量补肥即可。',
        'pruning_tips': '剪除老叶和侧芽，便于通风。',
        'propagation': '分株繁殖非常常见。',
        'common_problems': '叶片软烂通常与积水和低温有关。',
        'care_tips': '充足日照和少浇水是养好芦荟的关键。',
        'tags': ['新手友好', '耐旱', '喜光'],
    },
    {
        'name': '玉树',
        'scientific_name': 'Crassula ovata',
        'alias': '燕子掌',
        'wiki_title': '燕子掌',
        'category': '多肉植物',
        'summary': '玉树又名燕子掌，为景天科青锁龙属多年生肉质灌木，茎干粗壮、叶片肥厚有光泽，老株易形成木质化老桩，是兼具盆景感与多肉气质的经典品种。',
        'difficulty': 'easy',
        'light_requirement': 'full_sun',
        'water_requirement': 'low',
        'temperature_min': 5,
        'temperature_max': 32,
        'humidity': '偏干燥环境较好。',
        'soil_requirement': '疏松透气的多肉土或砂质土。',
        'fertilizer_tips': '生长期每月少量施肥一次。',
        'pruning_tips': '可通过修剪塑造树状造型。',
        'propagation': '叶插和枝插都容易。',
        'common_problems': '黑腐和掉叶常因积水或寒冷。',
        'care_tips': '给足光照并适当控水，枝叶会更紧凑。',
        'tags': ['耐旱', '喜光', '新手友好'],
    },
    {
        'name': '熊童子',
        'scientific_name': 'Cotyledon tomentosa',
        'alias': '绿熊',
        'wiki_title': '熊童子',
        'category': '多肉植物',
        'summary': '熊童子为景天科银波锦属多肉植物，叶片肥厚并密生白色短绒毛，叶端带有红色爪状齿，外形酷似小熊爪，是极具辨识度的萌系多肉。',
        'difficulty': 'medium',
        'light_requirement': 'full_sun',
        'water_requirement': 'low',
        'temperature_min': 5,
        'temperature_max': 30,
        'humidity': '喜欢凉爽干燥、通风良好的环境。',
        'soil_requirement': '颗粒比例较高的多肉专用土。',
        'fertilizer_tips': '薄肥少量即可。',
        'pruning_tips': '去掉徒长枝，保持株型。',
        'propagation': '扦插繁殖为主。',
        'common_problems': '夏季黑腐和掉叶是常见风险。',
        'care_tips': '重点避免高温闷湿，保持充足光照。',
        'tags': ['耐旱', '喜光', '观叶'],
    },
    {
        'name': '豆瓣兰',
        'scientific_name': 'Cymbidium goeringii',
        'alias': '春兰',
        'wiki_title': '春蘭',
        'category': '开花植物',
        'summary': '豆瓣兰常指春兰类国兰，为兰科兰属地生植物，叶片带形、姿态清秀，通常一葶一花、香气幽雅，是中国传统名兰和东方审美中极具代表性的观花植物。',
        'difficulty': 'hard',
        'light_requirement': 'indirect',
        'water_requirement': 'medium',
        'temperature_min': 5,
        'temperature_max': 28,
        'humidity': '偏爱通风和较高空气湿度。',
        'soil_requirement': '兰花专用透气颗粒基质。',
        'fertilizer_tips': '薄肥勤施，忌浓肥和高盐分。',
        'pruning_tips': '花谢后及时剪除花梗。',
        'propagation': '分株繁殖。',
        'common_problems': '烂根多由通风差和浇水不当导致。',
        'care_tips': '兰科植物养护的关键是透气、洁净和稳定。',
        'tags': ['观花', '香气', '高湿'],
    },
    {
        'name': '薄雪万年草',
        'scientific_name': 'Sedum hispanicum',
        'alias': '姬星美人近缘种',
        'wiki_title': '景天屬',
        'category': '多肉植物',
        'summary': '薄雪万年草为景天科景天属小型多肉植物，叶片细小密生、常呈蓝绿色，植株匍匐群生速度快，既适合拼盆铺面，也常被用作护盆草和微景观材料。',
        'difficulty': 'easy',
        'light_requirement': 'full_sun',
        'water_requirement': 'low',
        'temperature_min': -5,
        'temperature_max': 32,
        'humidity': '通风干燥更利于状态稳定。',
        'soil_requirement': '排水快的颗粒型多肉土。',
        'fertilizer_tips': '一般少量补肥即可。',
        'pruning_tips': '可修剪徒长枝进行补栽。',
        'propagation': '扦插极其容易。',
        'common_problems': '徒长和黑腐是常见问题。',
        'care_tips': '多晒太阳、少浇水，能更快形成紧密群生。',
        'tags': ['新手友好', '耐旱', '喜光'],
    },
    {
        'name': '空气凤梨',
        'scientific_name': 'Tillandsia',
        'alias': '铁兰',
        'wiki_title': '鐵蘭屬',
        'category': '观叶植物',
        'summary': '空气凤梨泛指凤梨科铁兰属气生植物，可不依赖土壤附着在木板、石头或器物上生长，形态多样、装饰性强，是很受欢迎的现代家居观叶植物。',
        'difficulty': 'medium',
        'light_requirement': 'indirect',
        'water_requirement': 'medium',
        'temperature_min': 10,
        'temperature_max': 30,
        'humidity': '喜欢通风和较高空气湿度。',
        'soil_requirement': '无需土壤，可附着在木板、石头或铁艺架上。',
        'fertilizer_tips': '偶尔用极低浓度叶面肥喷施即可。',
        'pruning_tips': '清理干枯叶片即可。',
        'propagation': '通过侧芽分株繁殖。',
        'common_problems': '叶尖发干多因湿度不足或浸泡后不通风。',
        'care_tips': '喷水或短时浸泡后务必倒置晾干。',
        'tags': ['观叶', '室内友好', '高湿'],
    },
]


USER_PLANT_SEEDS = [
    
    {'user': 'plant_lover1', 'plant': '白掌', 'nickname': '小白', 'notes': '第一盆养的植物，放在书桌旁', 'days_ago': 90},
    {'user': 'plant_lover1', 'plant': '富贵竹', 'nickname': '', 'notes': '水培的，办公室同事送的', 'days_ago': 60},
    {'user': 'plant_lover1', 'plant': '芦荟', 'nickname': '肉肉', 'notes': '养了快半年，分出来两棵小崽', 'days_ago': 150},
    {'user': 'plant_lover1', 'plant': '吊竹梅', 'nickname': '', 'notes': '摘心之后终于爆盆了', 'days_ago': 45},

    
    {'user': 'green_thumb', 'plant': '琴叶榕', 'nickname': '大琴', 'notes': '客厅C位，养了两年多', 'days_ago': 800},
    {'user': 'green_thumb', 'plant': '常春藤', 'nickname': '', 'notes': '挂在书架旁边，垂下来很漂亮', 'days_ago': 365},
    {'user': 'green_thumb', 'plant': '白掌', 'nickname': '', 'notes': '卧室养的，偶尔开花', 'days_ago': 500},
    {'user': 'green_thumb', 'plant': '富贵竹', 'nickname': '', 'notes': '厨房窗台水培', 'days_ago': 300},
    {'user': 'green_thumb', 'plant': '豆瓣绿', 'nickname': '小豆', 'notes': '桌面盆栽，特别好养', 'days_ago': 200},
    {'user': 'green_thumb', 'plant': '袖珍椰子', 'nickname': '', 'notes': '放在电脑旁边', 'days_ago': 180},
    {'user': 'green_thumb', 'plant': '鹿角蕨', 'nickname': '大鹿', 'notes': '最近上板了，每天都盯着看', 'days_ago': 30},

    
    {'user': 'balcony_garden', 'plant': '月季', 'nickname': '果汁', 'notes': '果汁阳台品种，花量稳定', 'days_ago': 730},
    {'user': 'balcony_garden', 'plant': '绣球', 'nickname': '无尽夏', 'notes': '今年终于调蓝了', 'days_ago': 400},
    {'user': 'balcony_garden', 'plant': '茉莉', 'nickname': '', 'notes': '夏天花香特别浓', 'days_ago': 365},
    {'user': 'balcony_garden', 'plant': '迷迭香', 'nickname': '', 'notes': '偶尔掐一点做菜', 'days_ago': 200},
    {'user': 'balcony_garden', 'plant': '罗勒', 'nickname': '', 'notes': '每年播种，长得飞快', 'days_ago': 60},
    {'user': 'balcony_garden', 'plant': '栀子花', 'nickname': '小栀', 'notes': '今年换盆后掉了不少苞', 'days_ago': 500},

    
    {'user': 'succulent_fan', 'plant': '玉树', 'nickname': '老桩', 'notes': '养了五年的老桩，快变成小树了', 'days_ago': 1800},
    {'user': 'succulent_fan', 'plant': '熊童子', 'nickname': '小熊', 'notes': '夏天差点黑腐，抢救回来了', 'days_ago': 300},
    {'user': 'succulent_fan', 'plant': '薄雪万年草', 'nickname': '', 'notes': '铺面用的，长得到处都是', 'days_ago': 200},
    {'user': 'succulent_fan', 'plant': '芦荟', 'nickname': '大芦荟', 'notes': '阳台边上放着，老皮实了', 'days_ago': 600},

    
    {'user': 'office_plant', 'plant': '白掌', 'nickname': '', 'notes': '北向窗边，最近状态好转', 'days_ago': 120},
    {'user': 'office_plant', 'plant': '袖珍椰子', 'nickname': '', 'notes': '工位上养的，挺耐阴', 'days_ago': 90},
    {'user': 'office_plant', 'plant': '豆瓣绿', 'nickname': '小胖', 'notes': '同事分了一棵给我', 'days_ago': 45},

    
    {'user': 'herb_garden', 'plant': '罗勒', 'nickname': '九层塔', 'notes': '做菜常用，消耗很快', 'days_ago': 40},
    {'user': 'herb_garden', 'plant': '迷迭香', 'nickname': '', 'notes': '养了一年多，味道越来越浓', 'days_ago': 400},

    
    {'user': 'fern_lover', 'plant': '鹿角蕨', 'nickname': '大鹿角', 'notes': '上板养的，状态非常好', 'days_ago': 180},
    {'user': 'fern_lover', 'plant': '合果芋', 'nickname': '', 'notes': '搭了攀爬柱，叶子越来越大', 'days_ago': 120},
    {'user': 'fern_lover', 'plant': '袖珍椰子', 'nickname': '', 'notes': '客厅角落的绿色点缀', 'days_ago': 90},

    
    {'user': 'flower_mama', 'plant': '绣球', 'nickname': '蓝梦', 'notes': '在调色中，希望能变蓝', 'days_ago': 100},
    {'user': 'flower_mama', 'plant': '月季', 'nickname': '粉红龙沙宝石', 'notes': '阳台种的，今年第一次开花', 'days_ago': 200},
    {'user': 'flower_mama', 'plant': '茉莉', 'nickname': '', 'notes': '孩子喜欢闻', 'days_ago': 150},

    
    {'user': 'weekend_gardener', 'plant': '玉树', 'nickname': '大树', 'notes': '养了三年，木质化了', 'days_ago': 1100},
    {'user': 'weekend_gardener', 'plant': '芦荟', 'nickname': '', 'notes': '分了好几棵给朋友', 'days_ago': 900},
    {'user': 'weekend_gardener', 'plant': '薄雪万年草', 'nickname': '', 'notes': '铺满了两个盆', 'days_ago': 300},
    {'user': 'weekend_gardener', 'plant': '熊童子', 'nickname': '小爪子', 'notes': '控养中，状态不错', 'days_ago': 250},

    
    {'user': 'cactus_king', 'plant': '玉树', 'nickname': '', 'notes': '先从多肉入门的', 'days_ago': 600},
    {'user': 'cactus_king', 'plant': '芦荟', 'nickname': '', 'notes': '阳台最耐晒的一盆', 'days_ago': 500},
    {'user': 'cactus_king', 'plant': '熊童子', 'nickname': '圆爪', 'notes': '圆叶品种，特别萌', 'days_ago': 200},

    
    {'user': 'expert_herbs', 'plant': '罗勒', 'nickname': '甜罗勒', 'notes': '甜罗勒品种，香气浓郁', 'days_ago': 800},
    {'user': 'expert_herbs', 'plant': '迷迭香', 'nickname': '蓝花迷', 'notes': '蓝花品种，耐寒性好', 'days_ago': 1200},
    {'user': 'expert_herbs', 'plant': '薄荷', 'nickname': '留兰香', 'notes': '留兰香品种，做饮品用', 'days_ago': 600},
    {'user': 'expert_herbs', 'plant': '茉莉', 'nickname': '', 'notes': '单瓣茉莉做花茶', 'days_ago': 900},

    
    {'user': 'expert_hydro', 'plant': '富贵竹', 'nickname': '水竹', 'notes': '水培示范用', 'days_ago': 500},
    {'user': 'expert_hydro', 'plant': '铜钱草', 'nickname': '', 'notes': '半水培实验组', 'days_ago': 400},
    {'user': 'expert_hydro', 'plant': '白掌', 'nickname': '', 'notes': '纯水培养了3年', 'days_ago': 1100},
    {'user': 'expert_hydro', 'plant': '常春藤', 'nickname': '', 'notes': '水培扦插母本', 'days_ago': 600},
    {'user': 'expert_hydro', 'plant': '合果芋', 'nickname': '', 'notes': '水培瓶中的观赏组', 'days_ago': 300},

    
    {'user': 'expert_bonsai', 'plant': '玉树', 'nickname': '老桩', 'notes': '10年老桩盆景', 'days_ago': 3600},
    {'user': 'expert_bonsai', 'plant': '鹿角蕨', 'nickname': '', 'notes': '大型板植作品', 'days_ago': 800},
    {'user': 'expert_bonsai', 'plant': '琴叶榕', 'nickname': '造型榕', 'notes': '修成独杆造型', 'days_ago': 1500},

    
    {'user': 'expert_pest', 'plant': '月季', 'nickname': '试验株', 'notes': '用来研究病害防治的', 'days_ago': 1000},
    {'user': 'expert_pest', 'plant': '常春藤', 'nickname': '', 'notes': '红蜘蛛防治研究', 'days_ago': 800},
    {'user': 'expert_pest', 'plant': '橡皮树', 'nickname': '', 'notes': '介壳虫防治案例', 'days_ago': 600},
    {'user': 'expert_pest', 'plant': '绣球', 'nickname': '', 'notes': '真菌病害观察', 'days_ago': 500},

    
    {'user': 'tropical_fan', 'plant': '合果芋', 'nickname': '白蝴蝶', 'notes': '搭了攀爬柱，叶片越来越大', 'days_ago': 120},
    {'user': 'tropical_fan', 'plant': '鹿角蕨', 'nickname': '', 'notes': '软木板上挂着，状态稳定', 'days_ago': 200},
    {'user': 'tropical_fan', 'plant': '常春藤', 'nickname': '', 'notes': '垂吊在窗边', 'days_ago': 300},
    {'user': 'tropical_fan', 'plant': '白掌', 'nickname': '白帆', 'notes': '水培转土培成功', 'days_ago': 180},
    {'user': 'tropical_fan', 'plant': '铜钱草', 'nickname': '', 'notes': '半水培状态，长得飞快', 'days_ago': 90},

    
    {'user': 'garden_dad', 'plant': '月季', 'nickname': '红龙', 'notes': '院子里地栽的，花量很大', 'days_ago': 500},
    {'user': 'garden_dad', 'plant': '茉莉', 'nickname': '', 'notes': '院子角落的老茉莉', 'days_ago': 400},
    {'user': 'garden_dad', 'plant': '罗勒', 'nickname': '九层塔', 'notes': '厨房旁种的，做菜常用', 'days_ago': 50},
    {'user': 'garden_dad', 'plant': '迷迭香', 'nickname': '', 'notes': '和罗勒种在一起', 'days_ago': 200},
    {'user': 'garden_dad', 'plant': '栀子花', 'nickname': '', 'notes': '院子里的大栀子', 'days_ago': 700},

    
    {'user': 'tiny_garden', 'plant': '玉树', 'nickname': '小树人', 'notes': '修成盆景造型', 'days_ago': 900},
    {'user': 'tiny_garden', 'plant': '薄雪万年草', 'nickname': '', 'notes': '做微景观的地被', 'days_ago': 300},
    {'user': 'tiny_garden', 'plant': '鹿角蕨', 'nickname': '小鹿', 'notes': '微型板植作品', 'days_ago': 150},
    {'user': 'tiny_garden', 'plant': '豆瓣绿', 'nickname': '', 'notes': '微缸里的配角', 'days_ago': 120},

    
    {'user': 'water_garden', 'plant': '富贵竹', 'nickname': '竹林', 'notes': '一整瓶十几根', 'days_ago': 400},
    {'user': 'water_garden', 'plant': '铜钱草', 'nickname': '铜钱', 'notes': '半水培养法，长势惊人', 'days_ago': 200},
    {'user': 'water_garden', 'plant': '白掌', 'nickname': '', 'notes': '土培转水培成功', 'days_ago': 180},
    {'user': 'water_garden', 'plant': '常春藤', 'nickname': '', 'notes': '水培扦插的新苗', 'days_ago': 60},
    {'user': 'water_garden', 'plant': '合果芋', 'nickname': '', 'notes': '水培瓶中养的', 'days_ago': 100},

    
    {'user': 'night_grower', 'plant': '袖珍椰子', 'nickname': '小椰', 'notes': '卧室里的伴侣', 'days_ago': 80},
    {'user': 'night_grower', 'plant': '豆瓣绿', 'nickname': '', 'notes': '床头柜上的小盆栽', 'days_ago': 50},
    {'user': 'night_grower', 'plant': '白掌', 'nickname': '', 'notes': '客厅角落', 'days_ago': 100},

    
    {'user': 'rooftop_girl', 'plant': '月季', 'nickname': '粉伊芙', 'notes': '天台主角，花期很长', 'days_ago': 600},
    {'user': 'rooftop_girl', 'plant': '绣球', 'nickname': '蓝球', 'notes': '三棵无尽夏', 'days_ago': 500},
    {'user': 'rooftop_girl', 'plant': '栀子花', 'nickname': '', 'notes': '大叶栀子，花期超香', 'days_ago': 400},
    {'user': 'rooftop_girl', 'plant': '茉莉', 'nickname': '', 'notes': '天台上的茉莉墙', 'days_ago': 350},
    {'user': 'rooftop_girl', 'plant': '常春藤', 'nickname': '', 'notes': '攀爬在栏杆上', 'days_ago': 500},
    {'user': 'rooftop_girl', 'plant': '迷迭香', 'nickname': '', 'notes': '角落种了一排', 'days_ago': 300},

    
    {'user': 'plant_doctor', 'plant': '橡皮树', 'nickname': '大黑', 'notes': '黑金刚品种，叶片特别厚', 'days_ago': 500},
    {'user': 'plant_doctor', 'plant': '琴叶榕', 'nickname': '', 'notes': '客厅的大叶植物', 'days_ago': 400},
    {'user': 'plant_doctor', 'plant': '月季', 'nickname': '', 'notes': '阳台上的病害实验对象', 'days_ago': 300},
    {'user': 'plant_doctor', 'plant': '常春藤', 'nickname': '', 'notes': '观察红蜘蛛用的', 'days_ago': 200},
    {'user': 'plant_doctor', 'plant': '白掌', 'nickname': '', 'notes': '办公桌上的', 'days_ago': 150},

    
    {'user': 'orchid_lover', 'plant': '蝴蝶兰', 'nickname': '大辣椒', 'notes': '红色大花品种', 'days_ago': 400},
    {'user': 'orchid_lover', 'plant': '蝴蝶兰', 'nickname': '满天红', 'notes': '粉色多花品种', 'days_ago': 350},
    {'user': 'orchid_lover', 'plant': '豆瓣兰', 'nickname': '老春兰', 'notes': '养了三年没开过花', 'days_ago': 1100},
    {'user': 'orchid_lover', 'plant': '君子兰', 'nickname': '大君', 'notes': '老株了，每年都开花', 'days_ago': 800},
]


CARE_RECORD_SEEDS = [
    
    {'user': 'plant_lover1', 'plant': '白掌', 'care_type': 'water', 'description': '浇透水，盆底有流出', 'days_ago': 2},
    {'user': 'plant_lover1', 'plant': '白掌', 'care_type': 'water', 'description': '表土干了，正常浇水', 'days_ago': 7},
    {'user': 'plant_lover1', 'plant': '白掌', 'care_type': 'fertilize', 'description': '用了稀薄液肥，生长期补肥', 'days_ago': 14},
    {'user': 'plant_lover1', 'plant': '芦荟', 'care_type': 'water', 'description': '半个月没浇了，今天浇透', 'days_ago': 3},
    {'user': 'plant_lover1', 'plant': '富贵竹', 'care_type': 'water', 'description': '换了一次水，水质还算清', 'days_ago': 5},
    {'user': 'plant_lover1', 'plant': '吊竹梅', 'care_type': 'prune', 'description': '摘心一次，剪下来的枝条插回盆里', 'days_ago': 10},

    
    {'user': 'green_thumb', 'plant': '琴叶榕', 'care_type': 'water', 'description': '浇透水，叶片也擦了一遍', 'days_ago': 3},
    {'user': 'green_thumb', 'plant': '琴叶榕', 'care_type': 'fertilize', 'description': '每月定期施一次均衡肥', 'days_ago': 10},
    {'user': 'green_thumb', 'plant': '常春藤', 'care_type': 'prune', 'description': '修了几根太长的枝条', 'days_ago': 7},
    {'user': 'green_thumb', 'plant': '常春藤', 'care_type': 'pest_control', 'description': '发现几只红蜘蛛，用水冲洗后喷了一次药', 'days_ago': 20},
    {'user': 'green_thumb', 'plant': '鹿角蕨', 'care_type': 'water', 'description': '上板后第一次浸泡补水', 'days_ago': 5},
    {'user': 'green_thumb', 'plant': '鹿角蕨', 'care_type': 'repot', 'description': '从盆栽转为上板，用水苔包裹根系', 'days_ago': 28},

    
    {'user': 'balcony_garden', 'plant': '月季', 'care_type': 'prune', 'description': '第一波花后修剪，回剪弱枝', 'days_ago': 15},
    {'user': 'balcony_garden', 'plant': '月季', 'care_type': 'fertilize', 'description': '花后追施磷钾水溶肥', 'days_ago': 14},
    {'user': 'balcony_garden', 'plant': '月季', 'care_type': 'pest_control', 'description': '发现蚜虫，用肥皂水喷了一遍', 'days_ago': 25},
    {'user': 'balcony_garden', 'plant': '绣球', 'care_type': 'water', 'description': '天热浇水量加大，早晚各一次', 'days_ago': 1},
    {'user': 'balcony_garden', 'plant': '绣球', 'care_type': 'fertilize', 'description': '用硫酸铝调酸，继续调色计划', 'days_ago': 7},
    {'user': 'balcony_garden', 'plant': '栀子花', 'care_type': 'repot', 'description': '换盆到酸性杜鹃土，希望能缓过来', 'days_ago': 20},
    {'user': 'balcony_garden', 'plant': '迷迭香', 'care_type': 'water', 'description': '控水浇了一点点，避免闷根', 'days_ago': 6},
    {'user': 'balcony_garden', 'plant': '罗勒', 'care_type': 'prune', 'description': '摘心采收，做了青酱', 'days_ago': 4},

    
    {'user': 'succulent_fan', 'plant': '玉树', 'care_type': 'prune', 'description': '修了两根徒长枝，保持树形', 'days_ago': 12},
    {'user': 'succulent_fan', 'plant': '玉树', 'care_type': 'water', 'description': '两周没浇了，今天浇透', 'days_ago': 5},
    {'user': 'succulent_fan', 'plant': '熊童子', 'care_type': 'water', 'description': '夏天控水，沿盆边少量给水', 'days_ago': 8},
    {'user': 'succulent_fan', 'plant': '熊童子', 'care_type': 'pest_control', 'description': '检查了一下根系，没有发现黑腐迹象', 'days_ago': 30},
    {'user': 'succulent_fan', 'plant': '薄雪万年草', 'care_type': 'prune', 'description': '剪掉徒长部分，重新铺回盆面', 'days_ago': 18},

    
    {'user': 'office_plant', 'plant': '白掌', 'care_type': 'water', 'description': '挪开空调出风口后第一次浇水', 'days_ago': 4},
    {'user': 'office_plant', 'plant': '白掌', 'care_type': 'other', 'description': '用湿布擦了叶片，去除灰尘', 'days_ago': 1},
    {'user': 'office_plant', 'plant': '袖珍椰子', 'care_type': 'water', 'description': '正常浇水', 'days_ago': 3},
    {'user': 'office_plant', 'plant': '豆瓣绿', 'care_type': 'water', 'description': '盆土还有点湿，先不浇', 'days_ago': 6},

    
    {'user': 'herb_garden', 'plant': '罗勒', 'care_type': 'prune', 'description': '摘心采叶，做了一份沙拉', 'days_ago': 3},
    {'user': 'herb_garden', 'plant': '罗勒', 'care_type': 'water', 'description': '天热消耗快，每天都要浇', 'days_ago': 1},
    {'user': 'herb_garden', 'plant': '迷迭香', 'care_type': 'prune', 'description': '轻剪了一下顶部，促侧枝', 'days_ago': 15},
    {'user': 'herb_garden', 'plant': '迷迭香', 'care_type': 'water', 'description': '见干见湿，控水浇透', 'days_ago': 7},

    
    {'user': 'fern_lover', 'plant': '鹿角蕨', 'care_type': 'water', 'description': '喷水打湿水苔，保持板面湿润', 'days_ago': 2},
    {'user': 'fern_lover', 'plant': '鹿角蕨', 'care_type': 'fertilize', 'description': '低浓度液肥喷施叶面', 'days_ago': 14},
    {'user': 'fern_lover', 'plant': '合果芋', 'care_type': 'water', 'description': '正常浇水，基质保持微湿', 'days_ago': 4},

    
    {'user': 'flower_mama', 'plant': '绣球', 'care_type': 'fertilize', 'description': '硫酸铝调酸第六周', 'days_ago': 7},
    {'user': 'flower_mama', 'plant': '绣球', 'care_type': 'water', 'description': '夏天不能缺水，浇到盆底流出', 'days_ago': 2},
    {'user': 'flower_mama', 'plant': '月季', 'care_type': 'pest_control', 'description': '发现白粉病，先摘掉病叶观察', 'days_ago': 5},
    {'user': 'flower_mama', 'plant': '茉莉', 'care_type': 'water', 'description': '保持盆土湿润', 'days_ago': 3},

    
    {'user': 'weekend_gardener', 'plant': '玉树', 'care_type': 'water', 'description': '周末统一检查，干透浇透', 'days_ago': 2},
    {'user': 'weekend_gardener', 'plant': '芦荟', 'care_type': 'water', 'description': '三周没管了，浇了一次', 'days_ago': 2},
    {'user': 'weekend_gardener', 'plant': '薄雪万年草', 'care_type': 'prune', 'description': '修剪了一批叶片准备送人', 'days_ago': 5},
    {'user': 'weekend_gardener', 'plant': '熊童子', 'care_type': 'water', 'description': '控水期间，少量给水', 'days_ago': 9},

    
    {'user': 'cactus_king', 'plant': '芦荟', 'care_type': 'water', 'description': '一个月没浇了，浇透', 'days_ago': 3},
    {'user': 'cactus_king', 'plant': '玉树', 'care_type': 'prune', 'description': '整理了一下造型', 'days_ago': 14},
    {'user': 'cactus_king', 'plant': '熊童子', 'care_type': 'water', 'description': '沿盆边少量给水', 'days_ago': 10},

    
    {'user': 'expert_herbs', 'plant': '罗勒', 'care_type': 'prune', 'description': '摘心打顶，促进分枝', 'days_ago': 3},
    {'user': 'expert_herbs', 'plant': '罗勒', 'care_type': 'water', 'description': '保持土壤湿润不积水', 'days_ago': 1},
    {'user': 'expert_herbs', 'plant': '迷迭香', 'care_type': 'prune', 'description': '修剪下部枝条改善通风', 'days_ago': 7},
    {'user': 'expert_herbs', 'plant': '薄荷', 'care_type': 'water', 'description': '夏天需要充足水分', 'days_ago': 1},
    {'user': 'expert_herbs', 'plant': '薄荷', 'care_type': 'prune', 'description': '大面积收割做薄荷水', 'days_ago': 5},
    {'user': 'expert_herbs', 'plant': '茉莉', 'care_type': 'fertilize', 'description': '花后追磷钾肥', 'days_ago': 10},

    
    {'user': 'expert_hydro', 'plant': '富贵竹', 'care_type': 'water', 'description': '换水并调整营养液浓度', 'days_ago': 2},
    {'user': 'expert_hydro', 'plant': '富贵竹', 'care_type': 'fertilize', 'description': '加微量元素补充液', 'days_ago': 7},
    {'user': 'expert_hydro', 'plant': '铜钱草', 'care_type': 'water', 'description': '半水培加水到标记线', 'days_ago': 1},
    {'user': 'expert_hydro', 'plant': '白掌', 'care_type': 'water', 'description': '换水清洗根系', 'days_ago': 3},
    {'user': 'expert_hydro', 'plant': '常春藤', 'care_type': 'prune', 'description': '取扦插枝条', 'days_ago': 14},
    {'user': 'expert_hydro', 'plant': '合果芋', 'care_type': 'water', 'description': '水培瓶换水', 'days_ago': 4},

    
    {'user': 'expert_bonsai', 'plant': '玉树', 'care_type': 'prune', 'description': '精细修剪造型枝', 'days_ago': 7},
    {'user': 'expert_bonsai', 'plant': '玉树', 'care_type': 'water', 'description': '控水养老桩', 'days_ago': 14},
    {'user': 'expert_bonsai', 'plant': '鹿角蕨', 'care_type': 'water', 'description': '板植浸泡半小时', 'days_ago': 3},
    {'user': 'expert_bonsai', 'plant': '琴叶榕', 'care_type': 'prune', 'description': '修剪侧芽保持独杆', 'days_ago': 10},

    
    {'user': 'expert_pest', 'plant': '月季', 'care_type': 'pest_control', 'description': '吡虫啉+阿维菌素轮换用药', 'days_ago': 3},
    {'user': 'expert_pest', 'plant': '月季', 'care_type': 'pest_control', 'description': '检查新梢蚜虫情况', 'days_ago': 1},
    {'user': 'expert_pest', 'plant': '常春藤', 'care_type': 'pest_control', 'description': '乙螨唑杀卵+联苯肼酯杀成螨', 'days_ago': 5},
    {'user': 'expert_pest', 'plant': '橡皮树', 'care_type': 'pest_control', 'description': '矿物油闷杀介壳虫', 'days_ago': 7},
    {'user': 'expert_pest', 'plant': '绣球', 'care_type': 'pest_control', 'description': '代森锰锌预防灰霉病', 'days_ago': 10},

    
    {'user': 'tropical_fan', 'plant': '合果芋', 'care_type': 'water', 'description': '保持土壤微湿', 'days_ago': 1},
    {'user': 'tropical_fan', 'plant': '合果芋', 'care_type': 'fertilize', 'description': '观叶植物液肥1:1000', 'days_ago': 14},
    {'user': 'tropical_fan', 'plant': '鹿角蕨', 'care_type': 'water', 'description': '软木板浸泡补水', 'days_ago': 3},
    {'user': 'tropical_fan', 'plant': '白掌', 'care_type': 'water', 'description': '水培换水加营养液', 'days_ago': 5},
    {'user': 'tropical_fan', 'plant': '铜钱草', 'care_type': 'water', 'description': '加水到花盆二分之一', 'days_ago': 2},
    {'user': 'tropical_fan', 'plant': '常春藤', 'care_type': 'prune', 'description': '修掉枯黄枝条', 'days_ago': 7},

    
    {'user': 'garden_dad', 'plant': '月季', 'care_type': 'pest_control', 'description': '打了一次多菌灵，预防黑斑病', 'days_ago': 5},
    {'user': 'garden_dad', 'plant': '月季', 'care_type': 'prune', 'description': '花后修剪残花和盲枝', 'days_ago': 3},
    {'user': 'garden_dad', 'plant': '月季', 'care_type': 'fertilize', 'description': '追施花多多二号催花', 'days_ago': 10},
    {'user': 'garden_dad', 'plant': '罗勒', 'care_type': 'water', 'description': '每天早上浇一次', 'days_ago': 1},
    {'user': 'garden_dad', 'plant': '罗勒', 'care_type': 'prune', 'description': '摘心促进分枝', 'days_ago': 8},
    {'user': 'garden_dad', 'plant': '栀子花', 'care_type': 'fertilize', 'description': '花期后补了磷钾肥', 'days_ago': 15},
    {'user': 'garden_dad', 'plant': '迷迭香', 'care_type': 'prune', 'description': '采了一把做烤肉', 'days_ago': 4},

    
    {'user': 'tiny_garden', 'plant': '玉树', 'care_type': 'prune', 'description': '修剪盆景枝条塑形', 'days_ago': 10},
    {'user': 'tiny_garden', 'plant': '玉树', 'care_type': 'water', 'description': '微量给水', 'days_ago': 5},
    {'user': 'tiny_garden', 'plant': '薄雪万年草', 'care_type': 'water', 'description': '喷壶喷雾保湿', 'days_ago': 2},
    {'user': 'tiny_garden', 'plant': '鹿角蕨', 'care_type': 'water', 'description': '板植浸泡10分钟', 'days_ago': 4},
    {'user': 'tiny_garden', 'plant': '豆瓣绿', 'care_type': 'water', 'description': '给微缸里的豆瓣绿补水', 'days_ago': 3},

    
    {'user': 'water_garden', 'plant': '富贵竹', 'care_type': 'water', 'description': '每周换水一次，加营养液', 'days_ago': 2},
    {'user': 'water_garden', 'plant': '富贵竹', 'care_type': 'fertilize', 'description': '加铁元素防叶片发黄', 'days_ago': 7},
    {'user': 'water_garden', 'plant': '铜钱草', 'care_type': 'water', 'description': '加水到盆边', 'days_ago': 1},
    {'user': 'water_garden', 'plant': '铜钱草', 'care_type': 'prune', 'description': '清理底部枯叶，留出空间', 'days_ago': 5},
    {'user': 'water_garden', 'plant': '白掌', 'care_type': 'water', 'description': '换水并清洗根系', 'days_ago': 3},
    {'user': 'water_garden', 'plant': '常春藤', 'care_type': 'water', 'description': '水培瓶加水', 'days_ago': 4},
    {'user': 'water_garden', 'plant': '合果芋', 'care_type': 'water', 'description': '水培瓶补水加液肥', 'days_ago': 6},

    
    {'user': 'night_grower', 'plant': '袖珍椰子', 'care_type': 'water', 'description': '下班回来浇水', 'days_ago': 2},
    {'user': 'night_grower', 'plant': '袖珍椰子', 'care_type': 'fertilize', 'description': '加了一点液肥', 'days_ago': 20},
    {'user': 'night_grower', 'plant': '豆瓣绿', 'care_type': 'water', 'description': '土表干了再浇', 'days_ago': 4},
    {'user': 'night_grower', 'plant': '白掌', 'care_type': 'water', 'description': '叶子有点耷拉，赶紧浇水', 'days_ago': 1},

    
    {'user': 'rooftop_girl', 'plant': '月季', 'care_type': 'water', 'description': '天台暴晒，早晚各浇一次', 'days_ago': 1},
    {'user': 'rooftop_girl', 'plant': '月季', 'care_type': 'pest_control', 'description': '吡虫啉灌根治蚜虫', 'days_ago': 6},
    {'user': 'rooftop_girl', 'plant': '月季', 'care_type': 'prune', 'description': '夏季轻剪，保留骨架枝', 'days_ago': 4},
    {'user': 'rooftop_girl', 'plant': '绣球', 'care_type': 'water', 'description': '夏天太渴了，一天浇两次', 'days_ago': 1},
    {'user': 'rooftop_girl', 'plant': '绣球', 'care_type': 'fertilize', 'description': '调蓝剂+硫酸铝', 'days_ago': 12},
    {'user': 'rooftop_girl', 'plant': '栀子花', 'care_type': 'water', 'description': '保持盆土湿润', 'days_ago': 2},
    {'user': 'rooftop_girl', 'plant': '茉莉', 'care_type': 'prune', 'description': '花谢后修剪促二次花', 'days_ago': 8},
    {'user': 'rooftop_girl', 'plant': '迷迭香', 'care_type': 'water', 'description': '控水，干透再浇', 'days_ago': 5},

    
    {'user': 'plant_doctor', 'plant': '橡皮树', 'care_type': 'water', 'description': '干透浇透', 'days_ago': 3},
    {'user': 'plant_doctor', 'plant': '橡皮树', 'care_type': 'prune', 'description': '砍头促分枝', 'days_ago': 30},
    {'user': 'plant_doctor', 'plant': '琴叶榕', 'care_type': 'water', 'description': '盆土干了两指深再浇', 'days_ago': 4},
    {'user': 'plant_doctor', 'plant': '琴叶榕', 'care_type': 'pest_control', 'description': '发现介壳虫，酒精棉签擦除', 'days_ago': 10},
    {'user': 'plant_doctor', 'plant': '月季', 'care_type': 'pest_control', 'description': '测试不同杀虫剂对红蜘蛛的效果', 'days_ago': 7},
    {'user': 'plant_doctor', 'plant': '常春藤', 'care_type': 'pest_control', 'description': '红蜘蛛严重，阿维菌素喷洒', 'days_ago': 5},
    {'user': 'plant_doctor', 'plant': '白掌', 'care_type': 'water', 'description': '办公室的白掌该浇水了', 'days_ago': 2},

    
    {'user': 'orchid_lover', 'plant': '蝴蝶兰', 'care_type': 'water', 'description': '水苔干了浸泡补水', 'days_ago': 3},
    {'user': 'orchid_lover', 'plant': '蝴蝶兰', 'care_type': 'fertilize', 'description': '花多多一号1:2000喷叶面', 'days_ago': 14},
    {'user': 'orchid_lover', 'plant': '豆瓣兰', 'care_type': 'water', 'description': '润而不湿，微微给水', 'days_ago': 5},
    {'user': 'orchid_lover', 'plant': '豆瓣兰', 'care_type': 'fertilize', 'description': '秋季追磷钾肥促花芽', 'days_ago': 20},
    {'user': 'orchid_lover', 'plant': '君子兰', 'care_type': 'water', 'description': '沿盆边慢浇', 'days_ago': 4},
    {'user': 'orchid_lover', 'plant': '君子兰', 'care_type': 'fertilize', 'description': '骨粉追肥', 'days_ago': 25},
]

__all__ = ['CATEGORY_DEFS', 'TAG_DEFS', 'PLANT_CATALOG', 'USER_PLANT_SEEDS', 'CARE_RECORD_SEEDS']
