TOPIC_FOLLOW_SEEDS = [
    {'topic': '观叶植物', 'followers': ['green_thumb', 'office_plant', 'expert_foliage', 'plant_lover1', 'fern_lover', 'tropical_fan', 'night_grower', 'plant_doctor', 'water_garden', 'expert_bonsai']},
    {'topic': '多肉养护', 'followers': ['succulent_fan', 'expert_succulent', 'plant_lover1', 'weekend_gardener', 'cactus_king', 'tiny_garden', 'expert_bonsai']},
    {'topic': '开花植物', 'followers': ['balcony_garden', 'expert_flower', 'green_thumb', 'flower_mama', 'rooftop_girl', 'garden_dad', 'orchid_lover', 'plant_doctor', 'expert_pest']},
    {'topic': '新手入门', 'followers': ['plant_lover1', 'office_plant', 'green_thumb', 'flower_mama', 'cactus_king', 'night_grower']},
    {'topic': '病虫害防治', 'followers': ['expert_foliage', 'green_thumb', 'expert_flower', 'fern_lover', 'plant_doctor', 'garden_dad', 'rooftop_girl', 'expert_pest']},
    {'topic': '阳台花园', 'followers': ['balcony_garden', 'expert_flower', 'succulent_fan', 'flower_mama', 'weekend_gardener', 'herb_garden', 'rooftop_girl', 'garden_dad', 'expert_herbs']},
    {'topic': '水培养护', 'followers': ['green_thumb', 'office_plant', 'fern_lover', 'water_garden', 'tropical_fan', 'expert_hydro']},
    {'topic': '香草种植', 'followers': ['balcony_garden', 'expert_flower', 'herb_garden', 'garden_dad', 'expert_herbs']},
    {'topic': '植物摄影', 'followers': ['green_thumb', 'succulent_fan', 'fern_lover', 'flower_mama', 'rooftop_girl', 'tiny_garden']},
    {'topic': '二手交换', 'followers': ['office_plant', 'weekend_gardener', 'cactus_king', 'orchid_lover', 'plant_lover1']},
]

POST_SEEDS = [
    {
        'author': 'office_plant',
        'topic': '观叶植物',
        'title': '办公室北向窗的白掌这样养，叶片终于立起来了',
        'content': '前阵子那盆白掌一直蔫着，我原来把它放在空调出风口旁边，叶片边缘干得很快。上周挪到北向窗边后，早上补一点清水擦叶，盆土表层发白再浇透，这两天叶片明显立起来了。办公室党如果也在养白掌，真的先把直吹空调这个坑避开。',
        'status': 'approved',
        'is_top': False,
        'is_essence': True,
        'view_count': 168,
        'like_users': ['green_thumb', 'plant_lover1', 'expert_foliage'],
        'comments': [
            {
                'author': 'expert_foliage',
                'content': '白掌最怕空调直吹和长期低湿，新叶发皱也常见于空气太干。你现在这个位置就很合适，可以继续保持盆土微湿但别闷根。',
                'like_users': ['office_plant', 'green_thumb'],
            },
            {
                'author': 'green_thumb',
                'content': '我办公室那盆也是挪开出风口后恢复的，北向窗虽然不晒，但散射光够稳定。',
                'like_users': ['office_plant'],
                'replies': [
                    {
                        'author': 'office_plant',
                        'reply_to': 'green_thumb',
                        'content': '原来不是我一个人踩坑，我准备再加个浅托盘增加周围湿度看看。',
                        'like_users': ['green_thumb'],
                    }
                ],
            },
        ],
    },
    {
        'author': 'succulent_fan',
        'topic': '多肉养护',
        'title': '玉树换成颗粒土后，叶色明显更紧凑',
        'content': '之前我那盆玉树一直是通用营养土，春天长得快但节间特别松。这个月换成颗粒比例更高的土，放在南向窗边控水后，叶色明显更深，顶部新叶也更紧凑了。老桩类多肉真的不能图省事一直用太闷的土。',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 142,
        'like_users': ['expert_succulent', 'plant_lover1', 'green_thumb', 'office_plant'],
        'comments': [
            {
                'author': 'expert_succulent',
                'content': '玉树想养出层次感，颗粒比例和光照确实都很关键。尤其春秋两季，宁可慢一点，也别让根长期泡在保水太强的介质里。',
                'like_users': ['succulent_fan', 'plant_lover1'],
            },
            {
                'author': 'plant_lover1',
                'content': '我刚入手一盆小玉树，还在犹豫要不要马上换土，看完更想早点动手了。',
                'like_users': ['succulent_fan'],
                'replies': [
                    {
                        'author': 'succulent_fan',
                        'reply_to': 'plant_lover1',
                        'content': '如果状态正常可以等服盆后再换，别在高温天折腾，成活率会更稳。',
                        'like_users': ['plant_lover1'],
                    }
                ],
            },
        ],
    },
    {
        'author': 'balcony_garden',
        'topic': '香草种植',
        'title': '把迷迭香和罗勒放在南向阳台，一个月的状态对比',
        'content': '同一批买回来的迷迭香和罗勒，我都放在南向阳台。罗勒长得飞快，几乎一周就能掐一次叶；迷迭香反而更喜欢我控水一点的节奏，盆土太湿时底部叶片会先发黄。两种香草虽然都爱光，但浇水逻辑差别真的挺大。',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 131,
        'like_users': ['expert_flower', 'green_thumb', 'office_plant', 'plant_lover1'],
        'comments': [
            {
                'author': 'expert_flower',
                'content': '罗勒属于长得快、需水也更积极的类型，常摘心还能持续分枝。迷迭香则更怕闷，盆再大一点反而容易出问题。',
                'like_users': ['balcony_garden', 'green_thumb'],
            },
            {
                'author': 'green_thumb',
                'content': '我之前总把两盆一起浇，结果迷迭香黄叶、罗勒徒长，后来分开管理才稳定。',
                'like_users': ['balcony_garden'],
            },
            {
                'author': 'office_plant',
                'content': '看完感觉我办公室那盆罗勒还是光照太少了，叶子薄得像纸。',
                'like_users': ['balcony_garden'],
            },
        ],
    },
    {
        'author': 'green_thumb',
        'topic': '水培养护',
        'title': '富贵竹水培别急着加营养液，先把根养稳',
        'content': '最近帮同事救了一瓶富贵竹，原来她刚买回来就连续加营养液，水还有点浑。其实前期先把底部修干净，前两周勤换水、避开暴晒，让新根长稳比什么都重要。根系一旦发白变壮，后面再少量补营养液会安全很多。',
        'status': 'approved',
        'is_top': False,
        'is_essence': True,
        'view_count': 156,
        'like_users': ['office_plant', 'expert_foliage', 'plant_lover1', 'balcony_garden'],
        'comments': [
            {
                'author': 'office_plant',
                'content': '这个真的有用，我之前就是买回来第一天就加营养液，结果没几天叶子就黄了一圈。',
                'like_users': ['green_thumb'],
            },
            {
                'author': 'expert_foliage',
                'content': '水培类植物前期最重要的是干净和通风，根系还没稳定时任何“补”都可能变成负担。',
                'like_users': ['green_thumb', 'office_plant'],
            },
        ],
    },
    {
        'author': 'expert_foliage',
        'topic': '观叶植物',
        'title': '鹿角蕨上板两周记录，湿度比浇水频率更重要',
        'content': '这次把一株鹿角蕨重新整理后上了软木板，很多朋友问我是不是要天天浇。其实比起机械地按天数补水，我更看空气湿度、板材干湿和叶片状态。板植环境通风快，水给得太猛反而容易让盾牌叶边缘发黑，稳定湿度比单纯高频浇水更重要。',
        'status': 'approved',
        'is_top': True,
        'is_essence': True,
        'view_count': 214,
        'like_users': ['green_thumb', 'office_plant', 'plant_lover1', 'expert_flower', 'succulent_fan'],
        'comments': [
            {
                'author': 'green_thumb',
                'content': '我之前就是看别人天天喷，结果板后水苔一直湿着，根反而闷坏了。',
                'like_users': ['expert_foliage', 'office_plant'],
            },
            {
                'author': 'office_plant',
                'content': '想问办公室空调环境是不是根本不适合板植鹿角蕨？我家里湿度常年只有40%左右。',
                'like_users': ['expert_foliage'],
                'replies': [
                    {
                        'author': 'expert_foliage',
                        'reply_to': 'office_plant',
                        'content': '如果湿度长期偏低，可以先盆养或提高局部湿度，再考虑上板，不然会很累。',
                        'like_users': ['office_plant', 'green_thumb'],
                    }
                ],
            },
        ],
    },
    {
        'author': 'expert_flower',
        'topic': '开花植物',
        'title': '月季第一波花后修剪复盘，二茬花苞已经冒出来了',
        'content': '今年第一波月季开完后，我没有拖太久，花后第三天就把残花连同弱枝一起回剪，并补了一次偏磷钾的水溶肥。现在不到三周，二茬花苞已经整齐冒出来。很多时候不是月季不愿意开，而是花后没有及时修剪和追肥。',
        'status': 'approved',
        'is_top': False,
        'is_essence': True,
        'view_count': 187,
        'like_users': ['balcony_garden', 'green_thumb', 'plant_lover1', 'office_plant'],
        'comments': [
            {
                'author': 'balcony_garden',
                'content': '我今年也试着更早回剪，二茬比去年整齐很多，看来节奏真的很关键。',
                'like_users': ['expert_flower'],
            },
            {
                'author': 'plant_lover1',
                'content': '想问新手第一次修剪是不是宁可轻一点，也不要一下剪太狠？',
                'like_users': ['expert_flower'],
            },
        ],
    },
    {
        'author': 'plant_lover1',
        'topic': '新手入门',
        'title': '吊竹梅爆盆其实不难，关键是舍得摘心',
        'content': '我养吊竹梅最大的变化，就是终于敢频繁摘心了。以前总怕剪了不好看，结果藤蔓越长越稀。最近每次新梢长出四五节就摘一下，顺手把剪下来的枝条插回盆边，现在整盆看起来就密很多，新手真的不要舍不得下手。',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 119,
        'like_users': ['office_plant', 'green_thumb', 'expert_foliage'],
        'comments': [
            {
                'author': 'office_plant',
                'content': '这一条对我太有用了，我那盆就是越留越稀，准备周末也试试看。',
                'like_users': ['plant_lover1'],
            },
            {
                'author': 'expert_foliage',
                'content': '吊竹梅恢复很快，摘心后给明亮散射光，颜色和分枝都会更漂亮。',
                'like_users': ['plant_lover1', 'green_thumb'],
            },
        ],
    },
    {
        'author': 'green_thumb',
        'topic': '植物摄影',
        'title': '阴天拍琴叶榕也能出片，分享我常用的取景角度',
        'content': '这几天一直阴天，很多朋友觉得拍不出植物的层次感。其实像琴叶榕这种叶片纹理明显的品种，阴天反而更容易拍出柔和质感。我习惯从侧前方四十五度拍，再让背景留一点呼吸感，叶脉和轮廓都会更干净。',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 97,
        'like_users': ['succulent_fan', 'office_plant', 'expert_foliage'],
        'comments': [
            {
                'author': 'succulent_fan',
                'content': '阴天拍多肉也很舒服，就是颜色会更淡一点，后期稍微拉一下对比就够了。',
                'like_users': ['green_thumb'],
            },
            {
                'author': 'office_plant',
                'content': '我总是把植物拍得又黑又灰，下次试试你说的侧前方角度。',
                'like_users': ['green_thumb'],
            },
        ],
    },
    {
        'author': 'fern_lover',
        'topic': '观叶植物',
        'title': '铁线蕨放在卫生间养了三个月，状态意外地好',
        'content': '之前铁线蕨在客厅怎么养都焦叶，后来搬到卫生间窗边，通风尚可且湿度天然就高。三个月下来几乎没再焦叶，新芽出的也很整齐。如果你家卫生间有窗，铁线蕨真的可以考虑放那里。',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 135,
        'like_users': ['expert_foliage', 'office_plant', 'green_thumb'],
        'comments': [
            {
                'author': 'expert_foliage',
                'content': '铁线蕨对湿度的要求确实高，卫生间是天然的高湿环境，只要通风没问题就很适合。',
                'like_users': ['fern_lover', 'green_thumb'],
            },
            {
                'author': 'office_plant',
                'content': '我家卫生间没窗，不然也想试试，铁线蕨在客厅真的太容易焦了。',
                'like_users': ['fern_lover'],
            },
        ],
    },
    {
        'author': 'herb_garden',
        'topic': '香草种植',
        'title': '薄荷繁殖太快，半年从一盆变成了五盆',
        'content': '当初就买了一棵薄荷苗，结果用水培扦插加土培分株折腾了半年，现在阳台上已经有五盆了。薄荷的生命力真的超出想象，随便掐一段枝条放水里几天就长根。唯一的问题是地下茎窜得太厉害，建议和别的植物隔开种。',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 108,
        'like_users': ['balcony_garden', 'expert_flower', 'plant_lover1'],
        'comments': [
            {
                'author': 'balcony_garden',
                'content': '我之前把薄荷和罗勒种在一个大盆里，结果薄荷越界了，罗勒被挤得没地方长。',
                'like_users': ['herb_garden'],
            },
            {
                'author': 'plant_lover1',
                'content': '好想试试水培扦插，听起来很简单。薄荷是不是随便哪个品种都行？',
                'like_users': ['herb_garden'],
                'replies': [
                    {
                        'author': 'herb_garden',
                        'reply_to': 'plant_lover1',
                        'content': '基本都行，留香薄荷和胡椒薄荷都很皮实，新手先从这两种开始。',
                        'like_users': ['plant_lover1'],
                    }
                ],
            },
        ],
    },
    {
        'author': 'flower_mama',
        'topic': '开花植物',
        'title': '第一次尝试给绣球调色，蓝色终于出来了',
        'content': '去年买的无尽夏一直开粉色，今年春天开始用硫酸铝调酸，浇了大概一个月，最近新开的花球终于偏蓝了。虽然还不是特别纯的蓝，但比起纯粉已经好看太多。关键是土壤要持续维持偏酸性，不能只浇一两次。',
        'status': 'approved',
        'is_top': False,
        'is_essence': True,
        'view_count': 176,
        'like_users': ['balcony_garden', 'expert_flower', 'green_thumb', 'herb_garden'],
        'comments': [
            {
                'author': 'expert_flower',
                'content': '调色关键是持续性，铝离子吸收需要时间。建议花期前一两个月就开始调，而且要注意浓度别太高，以免伤根。',
                'like_users': ['flower_mama', 'balcony_garden'],
            },
            {
                'author': 'balcony_garden',
                'content': '我也想把我那盆调成蓝色，请问硫酸铝大概什么比例兑水？',
                'like_users': ['flower_mama'],
                'replies': [
                    {
                        'author': 'flower_mama',
                        'reply_to': 'balcony_garden',
                        'content': '我用的大概是1克兑1升水，每周浇一次，连续四五周开始看到变化。',
                        'like_users': ['balcony_garden'],
                    }
                ],
            },
        ],
    },
    {
        'author': 'weekend_gardener',
        'topic': '多肉养护',
        'title': '周末集中浇水会有问题吗？工作日实在没时间管',
        'content': '平时工作日早出晚归，基本只有周末才能打理植物。我养了十来盆多肉，目前都是周六统一检查一遍，干透的就浇，没干的就跳过。这样的节奏会不会影响健康？有没有同样工作日很忙的朋友分享经验？',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 124,
        'like_users': ['succulent_fan', 'expert_succulent', 'cactus_king', 'office_plant'],
        'comments': [
            {
                'author': 'expert_succulent',
                'content': '多肉本来就不需要频繁浇水，周末集中检查、干透再浇的节奏其实挺合适的。比每天随手浇一点反而好。',
                'like_users': ['weekend_gardener', 'cactus_king'],
            },
            {
                'author': 'succulent_fan',
                'content': '我也是差不多的节奏，冬天甚至两三周才看一次。关键是别看着干就着急，多肉宁干勿湿。',
                'like_users': ['weekend_gardener'],
            },
            {
                'author': 'cactus_king',
                'content': '仙人掌更省心，我有几盆一个月没管也活得好好的。',
                'like_users': ['weekend_gardener', 'succulent_fan'],
            },
        ],
    },
    {
        'author': 'cactus_king',
        'topic': '多肉养护',
        'title': '仙人掌全日照和半日照养出来的差别真大',
        'content': '同一个品种的白鸟仙人球，我分了两盆放不同位置：一盆在南阳台全日照，一盆在东向窗只有半天光。两个月后全日照那盆刺座更密、球体更壮；半日照那盆虽然也长，但有点拉长迹象。仙人掌类还是得给足光。',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 113,
        'like_users': ['expert_succulent', 'succulent_fan', 'weekend_gardener'],
        'comments': [
            {
                'author': 'expert_succulent',
                'content': '仙人掌对光照的敏感度比很多多肉还高，光照不足除了徒长还会影响开花。球类品种几乎都建议全日照。',
                'like_users': ['cactus_king', 'weekend_gardener'],
            },
            {
                'author': 'succulent_fan',
                'content': '我那盆星兜也是，搬到南阳台后状态明显紧实了，以前在北侧完全不行。',
                'like_users': ['cactus_king'],
            },
        ],
    },
    {
        'author': 'expert_succulent',
        'topic': '新手入门',
        'title': '多肉入坑第一盆推荐清单，这五种最难养死',
        'content': '经常有新手问我第一盆多肉选什么好，这里统一推荐五种：玉树、芦荟、薄雪万年草、子持莲华、黄丽。它们的共同特点是对水肥不敏感、耐热耐寒范围广、扦插成活率高。新手最重要的是先建立信心，等这五种养稳了再考虑挑战难度更高的品种。',
        'status': 'approved',
        'is_top': True,
        'is_essence': True,
        'view_count': 242,
        'like_users': ['plant_lover1', 'office_plant', 'flower_mama', 'cactus_king', 'weekend_gardener', 'green_thumb'],
        'comments': [
            {
                'author': 'plant_lover1',
                'content': '我第一盆多肉就是芦荟，到现在快一年了还活着，确实很适合新手。',
                'like_users': ['expert_succulent', 'office_plant'],
            },
            {
                'author': 'flower_mama',
                'content': '薄雪万年草是不是就是铺在盆面上那种特别细小的？看起来好可爱。',
                'like_users': ['expert_succulent'],
                'replies': [
                    {
                        'author': 'expert_succulent',
                        'reply_to': 'flower_mama',
                        'content': '对，叶片很小，群生速度很快，铺面效果特别好。而且哪怕徒长了剪下来重新铺也能活。',
                        'like_users': ['flower_mama', 'plant_lover1'],
                    }
                ],
            },
            {
                'author': 'cactus_king',
                'content': '玉树养到老桩真的很有成就感，我那盆已经快变成小树了。',
                'like_users': ['expert_succulent', 'weekend_gardener'],
            },
        ],
    },
    {
        'author': 'fern_lover',
        'topic': '病虫害防治',
        'title': '蕨类的蚧壳虫反复发作，分享我试过的方法',
        'content': '家里的波士顿蕨去年冬天发了一次蚧壳虫，用酒精棉签擦掉后以为好了，结果过了一个月又冒出来。后来换了思路：先手动清理干净，然后用护花神按说明稀释后灌根加喷叶，连续三周每周一次，到现在半年没再复发。关键是要有耐心、连续处理，别只清一次就停。',
        'status': 'approved',
        'is_top': False,
        'is_essence': True,
        'view_count': 158,
        'like_users': ['expert_foliage', 'green_thumb', 'office_plant', 'herb_garden'],
        'comments': [
            {
                'author': 'expert_foliage',
                'content': '蚧壳虫确实很容易复发，原因是虫卵不容易一次清干净。连续三周处理的思路是对的，打断繁殖周期最重要。',
                'like_users': ['fern_lover', 'green_thumb'],
            },
            {
                'author': 'green_thumb',
                'content': '我之前也用过酒精擦，只管了两周又来了。看来还是需要系统性地处理。',
                'like_users': ['fern_lover'],
            },
        ],
    },
    {
        'author': 'balcony_garden',
        'topic': '阳台花园',
        'title': '阳台月季和地栽月季的差别，养了两年的体会',
        'content': '同品种的果汁阳台，我在老家地里种了一棵、阳台盆栽了一棵。地栽那棵几乎不用管，长势凶猛，花量大；阳台这棵需要勤浇水、勤追肥，花量小但花型反而更精致。两年下来的感受是：阳台月季不是不能养好，只是投入精力完全不同。',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 145,
        'like_users': ['expert_flower', 'flower_mama', 'green_thumb', 'weekend_gardener'],
        'comments': [
            {
                'author': 'expert_flower',
                'content': '阳台月季最大的挑战是盆土养分有限和通风条件差，白粉和红蜘蛛概率都比地栽高。坚持定期追肥和通风是关键。',
                'like_users': ['balcony_garden', 'flower_mama'],
            },
            {
                'author': 'flower_mama',
                'content': '我阳台那棵月季今年白粉挺严重的，不知道是不是通风不够。',
                'like_users': ['balcony_garden'],
                'replies': [
                    {
                        'author': 'balcony_garden',
                        'reply_to': 'flower_mama',
                        'content': '白粉一般和闷湿加通风差有关，可以把周围的植物疏一疏，给它留出空间。',
                        'like_users': ['flower_mama'],
                    }
                ],
            },
        ],
    },
    {
        'author': 'herb_garden',
        'topic': '新手入门',
        'title': '厨房窗台种薄荷的入门指南，从零开始到爆盆',
        'content': '很多朋友想在厨房窗台上种点香草，薄荷是最推荐的入门选择。只需要一个中等花盆、普通营养土、一段带节点的枝条就足够了。插入土中保持湿润，放在有散射光的窗台边，大概一周左右就能看到新芽。日常就是土面干了浇透，长出四五片叶子就可以开始摘着用了。',
        'status': 'approved',
        'is_top': False,
        'is_essence': True,
        'view_count': 189,
        'like_users': ['plant_lover1', 'office_plant', 'flower_mama', 'fern_lover', 'balcony_garden'],
        'comments': [
            {
                'author': 'plant_lover1',
                'content': '薄荷真是新手之光，我之前怎么浇都死不了，反而长得到处都是。',
                'like_users': ['herb_garden', 'office_plant'],
            },
            {
                'author': 'office_plant',
                'content': '办公室窗台光线够不够种薄荷？我这边是北向的。',
                'like_users': ['herb_garden'],
                'replies': [
                    {
                        'author': 'herb_garden',
                        'reply_to': 'office_plant',
                        'content': '北向光线偏弱，薄荷虽然能活但可能会徒长。可以试试看，实在不行就搬回家。',
                        'like_users': ['office_plant'],
                    }
                ],
            },
        ],
    },
    {
        'author': 'weekend_gardener',
        'topic': '二手交换',
        'title': '出一批多肉叶片和小苗，适合新手练手叶插',
        'content': '最近整理阳台修剪下来不少健康叶片和小侧芽，品种有玉树、薄雪万年草、黄丽、姬胧月、白牡丹等。量比较多，打包邮费我出。适合新手朋友练手叶插，成功率都比较高的品种。有兴趣的留言，我按先后顺序安排。',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 96,
        'like_users': ['plant_lover1', 'flower_mama', 'cactus_king'],
        'comments': [
            {
                'author': 'plant_lover1',
                'content': '想要！我正好想试试叶插，之前一直不敢动手。',
                'like_users': ['weekend_gardener'],
            },
            {
                'author': 'flower_mama',
                'content': '可以给小朋友带一份吗？我家孩子最近对种东西特别感兴趣。',
                'like_users': ['weekend_gardener'],
                'replies': [
                    {
                        'author': 'weekend_gardener',
                        'reply_to': 'flower_mama',
                        'content': '当然可以，我多给你配几片好出芽的品种，小朋友会很有成就感的。',
                        'like_users': ['flower_mama'],
                    }
                ],
            },
            {
                'author': 'cactus_king',
                'content': '有没有仙人掌的小崽？我想收集一些新品种。',
                'like_users': ['weekend_gardener'],
            },
        ],
    },
    {
        'author': 'green_thumb',
        'topic': '病虫害防治',
        'title': '龟背竹叶斑病的处理过程，从发现到恢复用了一个月',
        'content': '上个月我的龟背竹靠中间的一片大叶子出现了不规则的褐色斑点，一开始以为是晒伤，后来斑点扩大并且周围出现黄圈，确认是叶斑病。处理方法是先把病叶剪掉，然后用多菌灵稀释液喷全株，每周一次、喷了三次。同时减少浇水频率、加强通风。这周检查完全没有新斑了。',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 132,
        'like_users': ['expert_foliage', 'fern_lover', 'office_plant'],
        'comments': [
            {
                'author': 'expert_foliage',
                'content': '处理方式很标准。叶斑病的关键是发现后及时隔离病叶，避免交叉感染。另外环境闷湿是诱发因素，加强通风比用药更重要。',
                'like_users': ['green_thumb', 'fern_lover'],
            },
            {
                'author': 'fern_lover',
                'content': '多菌灵对预防真菌类问题确实有效，我也会定期喷一次做预防。',
                'like_users': ['green_thumb'],
            },
        ],
    },
    {
        'author': 'tropical_fan',
        'topic': '观叶植物',
        'title': '合果芋换了攀爬柱之后，叶子变大了整整一倍',
        'content': '之前我的合果芋一直散养在桌上，叶片大概巴掌大小。两个月前给它搭了一根椰棕攀爬柱，让气生根攀上去，现在新长的叶片已经比以前大了不止一倍，而且开始出现分裂叶。天南星科的植物真的有攀爬本能，给它支撑和高度就是最好的催化剂。',
        'status': 'approved',
        'is_top': False,
        'is_essence': True,
        'view_count': 162,
        'like_users': ['expert_foliage', 'fern_lover', 'green_thumb', 'office_plant', 'night_grower'],
        'comments': [
            {
                'author': 'expert_foliage',
                'content': '天南星科的攀爬属性很强，龟背竹、绿萝、合果芋都是如此。给支撑+保持湿度，叶形变化会非常明显。',
                'like_users': ['tropical_fan', 'fern_lover'],
            },
            {
                'author': 'fern_lover',
                'content': '我的合果芋也是加了柱子之后完全变了个样，感觉像换了一盆植物。',
                'like_users': ['tropical_fan'],
            },
            {
                'author': 'night_grower',
                'content': '请问攀爬柱用椰棕还是水苔好？我打算也给我的绿萝试试。',
                'like_users': ['tropical_fan'],
                'replies': [
                    {
                        'author': 'tropical_fan',
                        'reply_to': 'night_grower',
                        'content': '椰棕柱便宜好用，但保水性不如水苔柱。如果家里湿度够的话椰棕就行了。',
                        'like_users': ['night_grower'],
                    }
                ],
            },
        ],
    },
    {
        'author': 'garden_dad',
        'topic': '香草种植',
        'title': '和孩子一起在院子里种了一排薄荷，记录一下',
        'content': '上周末带孩子在院子角落种了一排薄荷，从超市买了两盆分出来的。孩子自己挖坑、浇水，特别有参与感。种下去一周多了，根已经扎稳，新芽冒出来好几个。计划等长密了做薄荷水给孩子喝。地栽薄荷生命力真的比盆栽强很多。',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 104,
        'like_users': ['herb_garden', 'flower_mama', 'balcony_garden', 'expert_flower'],
        'comments': [
            {
                'author': 'herb_garden',
                'content': '地栽薄荷要注意控制范围，不然它会往四周疯长把其他植物挤掉。建议用砖块或花盆底围一下。',
                'like_users': ['garden_dad', 'flower_mama'],
            },
            {
                'author': 'flower_mama',
                'content': '带孩子种植真的很有意义！我也想试试，请问薄荷对孩子安全吗？',
                'like_users': ['garden_dad'],
                'replies': [
                    {
                        'author': 'garden_dad',
                        'reply_to': 'flower_mama',
                        'content': '完全安全，薄荷本来就是食用香草，孩子摸了闻闻手还挺高兴的。',
                        'like_users': ['flower_mama'],
                    }
                ],
            },
        ],
    },
    {
        'author': 'water_garden',
        'topic': '水培养护',
        'title': '水培绿萝的根系修剪心得，别舍不得剪',
        'content': '水培绿萝养久了根系会特别密，整个瓶子被占满。很多人舍不得剪，其实定期修剪老根烂根对植物反而更好。我的做法是每两到三个月把根拿出来，剪掉底部发黑和过密的部分，只留白色健康根，换上干净水后恢复很快。',
        'status': 'approved',
        'is_top': False,
        'is_essence': True,
        'view_count': 143,
        'like_users': ['green_thumb', 'office_plant', 'night_grower', 'tropical_fan', 'plant_lover1'],
        'comments': [
            {
                'author': 'green_thumb',
                'content': '根系修剪确实重要，我之前一瓶水培绿萝差点被自己的根憋死，清理后立马精神了。',
                'like_users': ['water_garden', 'office_plant'],
            },
            {
                'author': 'office_plant',
                'content': '办公室的水培富贵竹根也很密了，看完准备周末清理一下。',
                'like_users': ['water_garden'],
            },
        ],
    },
    {
        'author': 'night_grower',
        'topic': '新手入门',
        'title': '上夜班的人适合养什么植物？光照时间完全反过来',
        'content': '我上夜班，白天睡觉会拉窗帘。家里的植物基本只有早上和傍晚各一两个小时的自然光。之前养了一盆绿萝还行，但文竹和多肉都不太好。想请教一下，像我这种光照条件极度有限的情况，适合养哪些品种？',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 138,
        'like_users': ['expert_foliage', 'office_plant', 'plant_lover1', 'water_garden'],
        'comments': [
            {
                'author': 'expert_foliage',
                'content': '绿萝、虎尾兰、袖珍椰子、豆瓣绿这些很耐阴。如果想丰富一点可以考虑补光灯，几十块的全光谱灯就够了。',
                'like_users': ['night_grower', 'office_plant', 'plant_lover1'],
            },
            {
                'author': 'office_plant',
                'content': '我办公室光照也差不多，袖珍椰子和豆瓣绿确实很稳，推荐。',
                'like_users': ['night_grower'],
            },
            {
                'author': 'water_garden',
                'content': '水培绿萝完全不挑光，而且不用操心土壤和浇水问题，适合你这种情况。',
                'like_users': ['night_grower'],
            },
        ],
    },
    {
        'author': 'rooftop_girl',
        'topic': '阳台花园',
        'title': '我的天台花园改造过程，从水泥地到花海',
        'content': '去年入住的时候天台就是一片空水泥地，我花了半年时间分批改造：先铺了防腐木地板，然后摆了大大小小的花盆，种了月季、绣球、铁线莲和一些藤蔓。现在春天一到简直像个小花园。最初的投入不大，关键是要有耐心，一点点来就好。',
        'status': 'approved',
        'is_top': True,
        'is_essence': True,
        'view_count': 256,
        'like_users': ['balcony_garden', 'expert_flower', 'flower_mama', 'garden_dad', 'green_thumb', 'herb_garden', 'tropical_fan'],
        'comments': [
            {
                'author': 'balcony_garden',
                'content': '太羡慕了！天台空间大真的可以发挥，我阳台就那么点地方。',
                'like_users': ['rooftop_girl', 'flower_mama'],
            },
            {
                'author': 'expert_flower',
                'content': '天台种月季和铁线莲光照肯定够，但夏天暴晒和大风要注意防护。有没有搭遮阳网？',
                'like_users': ['rooftop_girl'],
                'replies': [
                    {
                        'author': 'rooftop_girl',
                        'reply_to': 'expert_flower',
                        'content': '搭了，夏天正午会拉遮阳网，绣球尤其怕暴晒。冬天用挡风布围了一圈。',
                        'like_users': ['expert_flower', 'balcony_garden'],
                    }
                ],
            },
            {
                'author': 'garden_dad',
                'content': '太赞了！我家院子虽然有地种，但也想参考你的盆栽布局，特别好看。',
                'like_users': ['rooftop_girl'],
            },
        ],
    },
    {
        'author': 'plant_doctor',
        'topic': '病虫害防治',
        'title': '月季常见病害速查：白粉、黑斑、锈病一次讲清',
        'content': '月季是病害高发植物，这里简单梳理三种最常见的：白粉病——叶面白色粉状物，通风差时高发；黑斑病——叶片出现黑色圆斑伴黄化，多因连续淋雨或浇水溅到叶片；锈病——叶背出现橘黄色粉状孢子。处理共同点是：及时摘除病叶、加强通风、必要时用对应药剂。预防始终比治疗重要。',
        'status': 'approved',
        'is_top': True,
        'is_essence': True,
        'view_count': 231,
        'like_users': ['expert_flower', 'balcony_garden', 'flower_mama', 'rooftop_girl', 'garden_dad', 'green_thumb', 'herb_garden'],
        'comments': [
            {
                'author': 'expert_flower',
                'content': '总结得很全面。补充一点：月季的品种差异也很大，有些品种天生抗病性强。选品种的时候可以优先考虑抗病好的。',
                'like_users': ['plant_doctor', 'rooftop_girl', 'balcony_garden'],
            },
            {
                'author': 'flower_mama',
                'content': '我家月季就是黑斑病，收藏了这个帖子准备按方法处理。',
                'like_users': ['plant_doctor'],
            },
            {
                'author': 'rooftop_girl',
                'content': '去年天台的月季得了锈病，花了一个多月才控制住。通风确实是最重要的预防手段。',
                'like_users': ['plant_doctor', 'expert_flower'],
            },
        ],
    },
    {
        'author': 'orchid_lover',
        'topic': '开花植物',
        'title': '蝴蝶兰花期结束后怎么处理花梗，两种方案对比',
        'content': '蝴蝶兰花谢后花梗的处理一直有争议。方案一：从花梗第二三节处短截，有概率从侧芽再开一轮；方案二：等花梗完全枯萎后从基部剪掉，让植株休养。我两种都试过，短截确实偶尔能再开，但花朵更小、质量一般；剪掉养好根的话，下一季的花量和质量明显更好。个人更推荐方案二。',
        'status': 'approved',
        'is_top': False,
        'is_essence': True,
        'view_count': 178,
        'like_users': ['expert_flower', 'flower_mama', 'plant_lover1', 'office_plant', 'tropical_fan'],
        'comments': [
            {
                'author': 'expert_flower',
                'content': '同意方案二。蝴蝶兰能量有限，强行催二次花会消耗储备，影响来年花芽分化。好好养根才是长远之计。',
                'like_users': ['orchid_lover', 'flower_mama'],
            },
            {
                'author': 'flower_mama',
                'content': '我之前一直短截等二次花，难怪越来越弱，下次试试剪掉好好养。',
                'like_users': ['orchid_lover'],
            },
        ],
    },
    {
        'author': 'tiny_garden',
        'topic': '植物摄影',
        'title': '微型盆景拍摄技巧：用手机也能拍出高级感',
        'content': '拍微型盆景主要靠几个技巧：一是低角度平视拍摄，让盆景看起来像真正的大树；二是背景简洁，用纯色卡纸或毛毡就行；三是利用自然光，阴天的散射光最柔和；四是对焦在主干或最有层次的枝条上，让前后虚化。手机开微距模式或人像模式都能拍出不错的效果。',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 115,
        'like_users': ['green_thumb', 'succulent_fan', 'fern_lover', 'rooftop_girl'],
        'comments': [
            {
                'author': 'green_thumb',
                'content': '低角度平拍这个确实厉害，试了一下效果完全不一样。',
                'like_users': ['tiny_garden'],
            },
            {
                'author': 'succulent_fan',
                'content': '拍多肉群生的时候也可以用这个角度，感觉像在看一片小森林。',
                'like_users': ['tiny_garden', 'green_thumb'],
            },
        ],
    },
    {
        'author': 'water_garden',
        'topic': '水培养护',
        'title': '十种适合新手水培的植物推荐，成功率都在90%以上',
        'content': '整理了十种我自己水培过且成功率极高的品种：绿萝、富贵竹、铜钱草、白掌、吊兰、常春藤、合果芋、薄荷、文竹、袖珍椰子。其中绿萝和铜钱草几乎无脑成功，只要水干净基本不会出问题。白掌从土培转水培需要洗根过渡一下，但也不难。',
        'status': 'approved',
        'is_top': False,
        'is_essence': True,
        'view_count': 195,
        'like_users': ['plant_lover1', 'office_plant', 'night_grower', 'green_thumb', 'tropical_fan', 'flower_mama'],
        'comments': [
            {
                'author': 'office_plant',
                'content': '收藏了！办公室最适合水培，不用担心浇水过量的问题。',
                'like_users': ['water_garden', 'night_grower'],
            },
            {
                'author': 'night_grower',
                'content': '水培不需要频繁打理，特别适合我这种作息不规律的人。绿萝我已经养了一瓶，准备再水培一个铜钱草。',
                'like_users': ['water_garden'],
            },
            {
                'author': 'plant_lover1',
                'content': '白掌土转水培大概需要多久适应期？我那盆白掌想试试。',
                'like_users': ['water_garden'],
                'replies': [
                    {
                        'author': 'water_garden',
                        'reply_to': 'plant_lover1',
                        'content': '洗干净根后放水里，前两周每两天换一次水。大概两三周新水根就会长出来，之后就稳定了。',
                        'like_users': ['plant_lover1'],
                    }
                ],
            },
        ],
    },
    {
        'author': 'tropical_fan',
        'topic': '观叶植物',
        'title': '客厅雨林角落搭建记录：加湿器+补光灯+攀爬柱',
        'content': '在客厅角落搭了一个小型"雨林角"：龟背竹靠墙放、合果芋和绿萝沿攀爬柱往上爬、底下铺了鹿角蕨和蕨类。用了一台小加湿器保持湿度在60%以上，顶上装了一条全光谱补光灯带。运行一个月后，所有植物状态都比之前好，而且整个角落看起来特别有氛围。',
        'status': 'approved',
        'is_top': False,
        'is_essence': True,
        'view_count': 187,
        'like_users': ['fern_lover', 'expert_foliage', 'green_thumb', 'night_grower', 'water_garden', 'tiny_garden'],
        'comments': [
            {
                'author': 'fern_lover',
                'content': '太美了！加湿器对蕨类帮助确实很大，我也在考虑做一个类似的角落。',
                'like_users': ['tropical_fan', 'green_thumb'],
            },
            {
                'author': 'expert_foliage',
                'content': '补光灯带是个好方案，比台灯式补光更均匀。注意每天补光时长控制在8到12小时之间就好。',
                'like_users': ['tropical_fan', 'night_grower'],
            },
            {
                'author': 'night_grower',
                'content': '补光灯正好解决了我的问题！请问用什么品牌的灯带？',
                'like_users': ['tropical_fan'],
                'replies': [
                    {
                        'author': 'tropical_fan',
                        'reply_to': 'night_grower',
                        'content': '我用的是普通全光谱LED灯带，网上搜"植物补光灯带"就有很多选择，选色温4000K左右的就行。',
                        'like_users': ['night_grower'],
                    }
                ],
            },
        ],
    },
    {
        'author': 'garden_dad',
        'topic': '阳台花园',
        'title': '院子里种了几棵向日葵，孩子每天量高度',
        'content': '春天在院子空地上撒了几颗向日葵种子，现在最高的已经到了孩子的肩膀。孩子每天早上起来第一件事就是跑去看长高了没有，拿尺子量，还画在本子上当记录。虽然向日葵不算什么珍贵品种，但这个过程对孩子来说太有教育意义了。',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 127,
        'like_users': ['flower_mama', 'herb_garden', 'balcony_garden', 'rooftop_girl', 'plant_lover1'],
        'comments': [
            {
                'author': 'flower_mama',
                'content': '好有爱！孩子的成长和植物的生长同步记录，太有纪念价值了。',
                'like_users': ['garden_dad'],
            },
            {
                'author': 'herb_garden',
                'content': '向日葵成熟后可以让孩子自己收瓜子，体验完整的种植周期。',
                'like_users': ['garden_dad', 'flower_mama'],
            },
        ],
    },
    {
        'author': 'plant_doctor',
        'topic': '病虫害防治',
        'title': '红蜘蛛的三种防治方法，亲测哪种最有效',
        'content': '红蜘蛛是室内植物的噩梦，我试过三种方法：一是清水冲洗叶背，连续一周每天冲，适合轻度感染；二是用混合了几滴洗洁精的水喷叶，覆盖虫体使其窒息；三是用专用杀螨药喷洒。实测效果：轻度用方法一就够了，中度用方法二配合冲洗，重度才需要上药。关键是反复多次，不能只处理一遍。',
        'status': 'approved',
        'is_top': False,
        'is_essence': True,
        'view_count': 204,
        'like_users': ['expert_foliage', 'green_thumb', 'fern_lover', 'tropical_fan', 'office_plant', 'balcony_garden'],
        'comments': [
            {
                'author': 'expert_foliage',
                'content': '红蜘蛛最怕水，维持叶背湿润的环境就能有效预防。干燥闷热是它最喜欢的条件。',
                'like_users': ['plant_doctor', 'green_thumb', 'tropical_fan'],
            },
            {
                'author': 'green_thumb',
                'content': '方法二我也用过，确实有效但要注意洗洁精浓度别太高，不然叶片会受伤。',
                'like_users': ['plant_doctor'],
            },
            {
                'author': 'tropical_fan',
                'content': '自从用加湿器把湿度维持在60%以上，红蜘蛛基本没再来过。湿度真的是最好的预防。',
                'like_users': ['plant_doctor', 'fern_lover'],
            },
        ],
    },
    {
        'author': 'orchid_lover',
        'topic': '二手交换',
        'title': '出几盆蝴蝶兰开完花的复花苗，品种都不错',
        'content': '手上有六棵蝴蝶兰今年花期结束了，品种包括大辣椒、满天红、紫雨点等。都是成熟株，根系健康，只是花期过了需要养护到明年再开。适合有耐心等花的朋友。同城自取或者快递都行，但快递有风险提前说好。',
        'status': 'approved',
        'is_top': False,
        'is_essence': False,
        'view_count': 88,
        'like_users': ['plant_lover1', 'flower_mama', 'office_plant'],
        'comments': [
            {
                'author': 'flower_mama',
                'content': '想要一棵大辣椒练手，请问在哪个城市？',
                'like_users': ['orchid_lover'],
            },
            {
                'author': 'plant_lover1',
                'content': '蝴蝶兰复花需要春化吗？新手能养好吗？',
                'like_users': ['orchid_lover'],
                'replies': [
                    {
                        'author': 'orchid_lover',
                        'reply_to': 'plant_lover1',
                        'content': '大部分蝴蝶兰需要秋冬降温拉大昼夜温差来促花芽，不算特别难但需要一点耐心。',
                        'like_users': ['plant_lover1'],
                    }
                ],
            },
        ],
    },

    
    {
        'author': 'expert_herbs',
        'topic': '香草种植',
        'title': '阳台香草种植全攻略：从选品到收获',
        'content': '作为种了八年香草的人，给大家总结一套阳台香草种植方案。罗勒怕冷、喜光、需要频繁摘心；迷迭香耐旱、怕涝、通风是关键；薄荷生命力极强但要限根避免泛滥；百里香适合干燥环境。阳台种香草最重要的三点：充足的光照、良好的排水和定期采摘促进新生。每种香草的最佳播种时间和收获节奏也不同，大家有问题可以在评论区问我。',
        'status': 'approved',
        'is_top': True,
        'is_essence': True,
        'view_count': 356,
        'like_users': ['herb_garden', 'garden_dad', 'balcony_garden', 'rooftop_girl', 'flower_mama', 'tropical_fan'],
        'comments': [
            {
                'author': 'herb_garden',
                'content': '终于有专业的香草帖子了！请问罗勒的甜罗勒和紫叶罗勒哪种更适合做菜？',
                'like_users': ['expert_herbs', 'garden_dad'],
            },
            {
                'author': 'garden_dad',
                'content': '我北方庭院种的迷迭香每年冬天都冻死，有没有好的越冬方法？',
                'like_users': ['expert_herbs'],
                'replies': [
                    {
                        'author': 'expert_herbs',
                        'reply_to': 'garden_dad',
                        'content': '北方户外迷迭香越冬确实难，建议选蓝花品种耐寒性稍好，冬天移到室内朝南窗边，或者用保温棉包裹根部加覆盖物。',
                        'like_users': ['garden_dad', 'herb_garden'],
                    }
                ],
            },
        ],
    },
    {
        'author': 'expert_hydro',
        'topic': '水培养护',
        'title': '水培植物营养液配比指南：从入门到进阶',
        'content': '很多花友反馈水培植物养几个月就黄叶死掉，问题往往出在营养液上。水培营养液不是越浓越好：EC值建议控制在1.0-1.5ms/cm，pH保持在5.5-6.5。季节调节也重要：夏季高温少施或停施，冬季低温降低浓度。换水频率：夏季每周一次，冬季可以两周。白掌、合果芋、铜钱草三种植物的具体配方我在评论区单独说。',
        'status': 'approved',
        'is_top': True,
        'is_essence': True,
        'view_count': 428,
        'like_users': ['water_garden', 'tropical_fan', 'office_plant', 'night_grower', 'green_thumb', 'fern_lover'],
        'comments': [
            {
                'author': 'water_garden',
                'content': '终于看到专业的水培帖了！请问富贵竹用通用营养液可以吗还是要专用的？',
                'like_users': ['expert_hydro', 'tropical_fan'],
            },
            {
                'author': 'tropical_fan',
                'content': '合果芋水培根系变得黏糊糊的，是营养液浓度太高还是换水太少？',
                'like_users': ['expert_hydro'],
                'replies': [
                    {
                        'author': 'expert_hydro',
                        'reply_to': 'tropical_fan',
                        'content': '根系发黏说明根腐了，通常是水中缺氧导致的。建议换水时把根系冲洗干净，剪掉烂根，容器中加个气泡石增氧效果会很好。',
                        'like_users': ['tropical_fan', 'water_garden'],
                    }
                ],
            },
        ],
    },
    {
        'author': 'expert_bonsai',
        'topic': '观叶植物',
        'title': '玉树老桩盆景造型入门：三年磨一桩',
        'content': '玉树虽然普通，但养成老桩盆景后气质完全不同。造型要点：1.选3年以上的老株，主干至少拇指粗；2.砍头后等待萌芽，选留主要枝条；3.用铝线绑扎引导枝条走向但不能太紧；4.控水+全光照让木质化更快；5.配适当的浅盆和铺面石。整个过程至少需要1-2年时间，急不得。养桩最重要的心态是慢和等。',
        'status': 'approved',
        'is_top': False,
        'is_essence': True,
        'view_count': 213,
        'like_users': ['tiny_garden', 'cactus_king', 'succulent_fan', 'fern_lover', 'weekend_gardener'],
        'comments': [
            {
                'author': 'tiny_garden',
                'content': '受教了！我那棵9年的玉树一直不敢动手修剪，怕剪坏了。您觉得现在夏天适合砍头吗？',
                'like_users': ['expert_bonsai'],
            },
            {
                'author': 'cactus_king',
                'content': '玉树做盆景太有意思了，请问仙人柱类也能做类似造型吗？',
                'like_users': ['expert_bonsai', 'tiny_garden'],
                'replies': [
                    {
                        'author': 'expert_bonsai',
                        'reply_to': 'cactus_king',
                        'content': '仙人柱类可以做另一种风格的组合盆栽，但不适合传统盆景造型。可以搭配石头和苔藓做成沙漠微景观。',
                        'like_users': ['cactus_king'],
                    }
                ],
            },
        ],
    },
    {
        'author': 'expert_pest',
        'topic': '病虫害防治',
        'title': '月季常见病虫害综合防治方案（持续更新）',
        'content': '月季是出了名的"药罐子"，但掌握了综合防治思路就能大大减少问题。\n预防为主：定期喷代森锰锌预防黑斑、白粉；修剪后涂抹愈合剂防感染；保持通风降低湿度。\n虫害分类：蚜虫用吡虫啉灌根+喷洒；红蜘蛛用阿维菌素+乙螨唑轮换；介壳虫用矿物油+速扑杀。\n关键原则：不同药剂交替使用避免抗性，严重时可以考虑系统性内吸药剂。\n有具体问题欢迎评论区提问，我会详细回复。',
        'status': 'approved',
        'is_top': True,
        'is_essence': True,
        'view_count': 512,
        'like_users': ['plant_doctor', 'rooftop_girl', 'flower_mama', 'garden_dad', 'balcony_garden', 'green_thumb', 'expert_flower'],
        'comments': [
            {
                'author': 'plant_doctor',
                'content': '太专业了！请问关于轮换用药，您是怎么制定用药周期表的？比如阿维菌素这次用了，下次间隔多久换乙螨唑？',
                'like_users': ['expert_pest', 'rooftop_girl', 'flower_mama'],
            },
            {
                'author': 'rooftop_girl',
                'content': '我天台月季红蜘蛛每年夏天都爆发，用了好几种药都反复。这个轮换方案我试试看！',
                'like_users': ['expert_pest', 'plant_doctor'],
                'replies': [
                    {
                        'author': 'expert_pest',
                        'reply_to': 'rooftop_girl',
                        'content': '天台通风好但紫外线强，药剂可以在傍晚施用减少光解。红蜘蛛建议7天一个疗程，前两天集中喷药，间隔5天后换另一种再喷，连续三轮基本能控制住。',
                        'like_users': ['rooftop_girl', 'plant_doctor', 'flower_mama'],
                    }
                ],
            },
            {
                'author': 'flower_mama',
                'content': '白粉病每年春天都犯，今年按照预防方案提前喷药果然好多了。',
                'like_users': ['expert_pest', 'garden_dad'],
            },
        ],
    },
]

QUESTION_SEEDS = [
    {
        'author': 'office_plant',
        'title': '白掌新叶发皱、老叶下垂，是缺水还是空调太干？',
        'content': '办公室北向窗边养了一盆白掌，最近新叶发皱，老叶也会在下午明显下垂。盆土摸起来还算湿，但空调开得比较久。请问这种情况更像缺水、闷根，还是单纯空气太干？',
        'plant_type': '白掌',
        'status': 'answered',
        'view_count': 103,
        'is_urgent': False,
        'bounty': 20,
        'answers': [
            {
                'author': 'expert_foliage',
                'content': '从你的描述看，更像空调直吹叠加空气湿度过低。白掌在盆土不干的前提下还下垂，往往不是缺水而是蒸腾失衡。先避开出风口，检查根系是否有异味，再把浇水节奏控制在表土微干后浇透。',
                'is_accepted': True,
                'like_users': ['office_plant', 'green_thumb', 'plant_lover1'],
            },
            {
                'author': 'green_thumb',
                'content': '如果盆土已经有点板结，也会出现表面湿、里面根不舒服的情况。我会顺便检查一下排水孔和介质透气性。',
                'is_accepted': False,
                'like_users': ['office_plant'],
            },
        ],
    },
    {
        'author': 'plant_lover1',
        'title': '熊童子夏天掉叶很快，黑杆前还能救吗？',
        'content': '最近气温高了以后，我那盆熊童子开始从底部掉叶，昨天还发现有一根枝条发黑变软。放在南向窗边，前几天因为怕干我浇得比较勤。现在这种状态还能抢救吗，需要立刻砍头还是先停水？',
        'plant_type': '熊童子',
        'status': 'answered',
        'view_count': 141,
        'is_urgent': True,
        'bounty': 50,
        'answers': [
            {
                'author': 'expert_succulent',
                'content': '高温期熊童子最怕闷湿，枝条发黑基本要优先判断黑腐。建议立刻停水，把发黑部分切到组织健康的位置，伤口晾干后再换到更通风的环境。短期内不要施肥，也不要想着一次浇透“补回来”。',
                'is_accepted': True,
                'like_users': ['plant_lover1', 'succulent_fan', 'office_plant'],
            },
            {
                'author': 'succulent_fan',
                'content': '我去年也遇到过，抢救时最有效的是先果断砍掉坏掉的枝，再把剩下健康枝条重新扦插，不然黑腐扩得很快。',
                'is_accepted': False,
                'like_users': ['plant_lover1'],
            },
        ],
    },
    {
        'author': 'balcony_garden',
        'title': '栀子花换盆后一直掉花苞，土是酸性的也没缓过来',
        'content': '我的栀子花开花前换了一次盆，介质用了偏酸性的杜鹃土，也有正常见光，但这两周一直掉花苞。叶子暂时还绿，就是花苞一碰就掉。想问这更像缓苗期正常反应，还是换盆时伤根太多了？',
        'plant_type': '栀子花',
        'status': 'answered',
        'view_count': 126,
        'is_urgent': False,
        'bounty': 30,
        'answers': [
            {
                'author': 'expert_flower',
                'content': '栀子花在孕蕾期本来就不适合大动盆，掉苞大概率和换盆导致的根系波动有关。现在先别再折腾，保持散射光和稳定湿度，浇水不要忽干忽湿，等这一轮缓过去后再看新梢状态。',
                'is_accepted': True,
                'like_users': ['balcony_garden', 'green_thumb'],
            },
            {
                'author': 'green_thumb',
                'content': '如果最近还有连续阴雨或通风差，掉苞会更明显。我家的栀子只要环境一变就很敏感。',
                'is_accepted': False,
                'like_users': ['balcony_garden'],
            },
        ],
    },
    {
        'author': 'green_thumb',
        'title': '鹿角蕨板植后盾牌叶边缘发黑，是积水还是正常老化？',
        'content': '一株鹿角蕨上板大概十天，最近发现盾牌叶边缘有一圈发黑，摸起来不是完全软烂，但看着有点吓人。平时两三天喷一次，环境通风还可以。想确认一下这种边缘发黑更像浇多了，还是新老叶交替的正常情况？',
        'plant_type': '鹿角蕨',
        'status': 'answered',
        'view_count': 117,
        'is_urgent': False,
        'bounty': 20,
        'answers': [
            {
                'author': 'expert_foliage',
                'content': '如果发黑主要集中在盾牌叶老边缘，且组织没有明显发臭、化水，很多时候是旧组织自然退化，不一定是病。真正需要警惕的是中心点附近发黑、持续扩散，或者板后介质一直湿冷。',
                'is_accepted': True,
                'like_users': ['green_thumb', 'office_plant'],
            },
            {
                'author': 'office_plant',
                'content': '学到了，我之前一看到发黑就以为是烂掉，原来还要看位置和扩散速度。',
                'is_accepted': False,
                'like_users': ['green_thumb'],
            },
        ],
    },
    {
        'author': 'office_plant',
        'title': '北向办公位想养一盆耐阴植物，袖珍椰子和文竹谁更稳？',
        'content': '工位靠北向窗，没有直射光，空调常年开着。我想放一盆比较耐看的绿植，在袖珍椰子和文竹之间纠结。希望不要太容易焦尖，也不要动不动就大面积黄叶。大家更推荐哪一种？',
        'plant_type': '袖珍椰子',
        'status': 'answered',
        'view_count': 92,
        'is_urgent': False,
        'bounty': 15,
        'answers': [
            {
                'author': 'expert_foliage',
                'content': '如果是典型办公位，我会优先推荐袖珍椰子。它对光照的容忍度更高，环境稳定时不容易像文竹那样因为空气干燥或位置变化出现大面积黄枝。文竹更秀气，但也更挑湿度和通风。',
                'is_accepted': True,
                'like_users': ['office_plant', 'green_thumb'],
            },
            {
                'author': 'green_thumb',
                'content': '我两种都养过，文竹好看但很看心情，办公室稍微干一点就容易黄。袖珍椰子更稳妥。',
                'is_accepted': False,
                'like_users': ['office_plant'],
            },
        ],
    },
    {
        'author': 'balcony_garden',
        'title': '迷迭香盆土总是表干里湿，应该换更小盆还是加颗粒？',
        'content': '迷迭香种在一个相对深的塑料盆里，最近发现盆面看起来干得很快，但扒下去里面还是湿的。担心这样下去容易闷根。现在是更适合换小一号的盆，还是直接提高颗粒比例会更有效？',
        'plant_type': '迷迭香',
        'status': 'open',
        'view_count': 88,
        'is_urgent': False,
        'bounty': 20,
        'answers': [
            {
                'author': 'expert_flower',
                'content': '迷迭香怕的是根区长期湿闷，如果盆明显偏深偏大，我会先从容器尺寸入手，再配合增加颗粒。单纯只加颗粒但继续用不合适的大盆，改善会比较有限。',
                'is_accepted': False,
                'like_users': ['balcony_garden'],
            }
        ],
    },
    {
        'author': 'succulent_fan',
        'title': '薄雪万年草徒长后能直接平铺回盆里吗？',
        'content': '前段时间阴天太多，薄雪万年草有点徒长，茎节拉开了。想把徒长部分剪下来直接平铺回原盆里做补栽，不知道这样会不会容易黑腐，还是应该先晾两天再铺？',
        'plant_type': '薄雪万年草',
        'status': 'answered',
        'view_count': 95,
        'is_urgent': False,
        'bounty': 10,
        'answers': [
            {
                'author': 'expert_succulent',
                'content': '薄雪万年草扦插能力很强，徒长后补栽是常规操作。为了稳妥一些，最好先把剪口晾半天到一天，再平铺在偏干的介质表面，前几天不要急着大水灌透。',
                'is_accepted': True,
                'like_users': ['succulent_fan', 'plant_lover1'],
            },
            {
                'author': 'plant_lover1',
                'content': '我之前直接铺也活了，但天气闷的时候确实更容易黑掉，晾一下会安心很多。',
                'is_accepted': False,
                'like_users': ['succulent_fan'],
            },
        ],
    },
    {
        'author': 'flower_mama',
        'title': '绣球浇了硫酸铝还是不变蓝，是品种问题还是用量不够？',
        'content': '我买了一盆标注"无尽夏"的绣球，从开春就开始用硫酸铝每周浇一次，但最近开花还是偏粉色，完全看不到蓝色的趋势。不确定是品种标错了、土壤pH还是很高、还是用量不够。有没有同样调色成功的朋友给点建议？',
        'plant_type': '绣球',
        'status': 'answered',
        'view_count': 118,
        'is_urgent': False,
        'bounty': 25,
        'answers': [
            {
                'author': 'expert_flower',
                'content': '无尽夏确实可以调蓝，但有几个前提：一是基质本身不能太碱，建议用pH低于6的酸性土；二是硫酸铝的浓度要够，1克/升每周一次至少连续6到8周才见效；三是已经显色的花球很难再改变，要从花芽分化前就开始调。如果下一轮花还是粉色，可能需要换土。',
                'is_accepted': True,
                'like_users': ['flower_mama', 'balcony_garden', 'green_thumb'],
            },
            {
                'author': 'balcony_garden',
                'content': '我第一年调也没成功，第二年换了纯泥炭土后才终于蓝了。土壤基底很关键。',
                'is_accepted': False,
                'like_users': ['flower_mama'],
            },
        ],
    },
    {
        'author': 'fern_lover',
        'title': '铁线蕨叶片持续干枯，换了位置还是不行怎么办？',
        'content': '铁线蕨买回来第一周就开始焦叶，先从叶尖干起来，后来整片叶子都枯了。我试过搬到卫生间、加湿器旁边、罩塑料袋闷养，但新叶虽然有冒出来，老叶还是继续枯。现在整盆看起来半死不活的，是不是该把枯叶全剪掉重新养？',
        'plant_type': '铁线蕨',
        'status': 'answered',
        'view_count': 104,
        'is_urgent': False,
        'bounty': 20,
        'answers': [
            {
                'author': 'expert_foliage',
                'content': '铁线蕨到新环境焦叶是很常见的适应反应。建议把所有枯叶剪到根部，保持盆土微湿但不积水，放在稳定的高湿环境里不要再频繁移动。新芽冒出后会逐渐适应你家的环境。这种蕨类最怕反复换位置。',
                'is_accepted': True,
                'like_users': ['fern_lover', 'green_thumb', 'office_plant'],
            },
            {
                'author': 'green_thumb',
                'content': '我之前也遇到过，剃头之后反而恢复了。铁线蕨生命力其实挺强的，就是特别敏感。',
                'is_accepted': False,
                'like_users': ['fern_lover'],
            },
        ],
    },
    {
        'author': 'cactus_king',
        'title': '仙人掌冬天到底要不要完全断水？',
        'content': '看到不同的说法：有人说冬天必须完全断水让仙人掌休眠，有人说偶尔可以沿盆边少量给水。我在北方，冬天有暖气，室温大概20度左右，这种情况是断水好还是少量给水好？',
        'plant_type': '仙人掌',
        'status': 'answered',
        'view_count': 97,
        'is_urgent': False,
        'bounty': 15,
        'answers': [
            {
                'author': 'expert_succulent',
                'content': '如果室温稳定在20度左右，仙人掌其实没有完全进入休眠。这种情况下可以每月沿盆边少量给水一次，让根系不至于完全干枯。真正需要断水的是没有暖气、室温低于10度的环境。关键看温度而不是看季节。',
                'is_accepted': True,
                'like_users': ['cactus_king', 'weekend_gardener', 'succulent_fan'],
            },
            {
                'author': 'succulent_fan',
                'content': '我冬天有暖气也会大概一个月给一次，量很少就行。完全断水的话春天恢复反而慢。',
                'is_accepted': False,
                'like_users': ['cactus_king'],
            },
        ],
    },
    {
        'author': 'herb_garden',
        'title': '薄荷叶片上出现白色粉末状东西，是白粉病吗？',
        'content': '阳台上的留兰香薄荷最近叶片正面出现了一些白色粉末状的东西，轻轻一碰能擦掉。整株还算精神，但扩散得比较快，已经有三四片叶子了。不确定是白粉病还是其他问题，想请教一下怎么处理比较好？',
        'plant_type': '薄荷',
        'status': 'answered',
        'view_count': 89,
        'is_urgent': True,
        'bounty': 30,
        'answers': [
            {
                'author': 'expert_flower',
                'content': '从描述看大概率是白粉病，薄荷在通风不好或湿度忽高忽低时比较容易得。处理方式：先把有白粉的叶片全部摘掉扔掉，不要留在盆旁边。然后用小苏打水（1茶匙小苏打兑1升水）喷全株，每三天一次，连续两到三周。同时改善通风、减少叶片喷水。因为薄荷是食用植物，不建议用化学农药。',
                'is_accepted': True,
                'like_users': ['herb_garden', 'balcony_garden', 'green_thumb'],
            },
            {
                'author': 'balcony_garden',
                'content': '我去年薄荷也得过白粉病，加强通风后自然好了。如果严重的话可以直接剃头让它重新长。',
                'is_accepted': False,
                'like_users': ['herb_garden'],
            },
        ],
    },
    {
        'author': 'weekend_gardener',
        'title': '多肉叶插总是出根不出芽，到底哪里出了问题？',
        'content': '最近用黄丽和姬胧月的叶片做叶插实验，放在干燥的颗粒土表面。大部分叶片都长出了根，但已经一个多月了还是没有冒芽。根倒是越长越长，叶片也开始皱缩但没腐烂。请问这种情况是还需要等，还是操作有问题？',
        'plant_type': '多肉',
        'status': 'open',
        'view_count': 105,
        'is_urgent': False,
        'bounty': 20,
        'answers': [
            {
                'author': 'expert_succulent',
                'content': '出根不出芽的常见原因有几种：光照太强导致叶片消耗太快、温度不够理想、或者品种本身出芽慢。黄丽和姬胧月都是出芽比较友好的品种，建议放到明亮但不直晒的位置，温度保持在20到25度之间，根长出来后可以轻轻覆一层薄土在根上面，等待就好。有的叶片确实需要两三个月才出芽。',
                'is_accepted': False,
                'like_users': ['weekend_gardener', 'plant_lover1'],
            },
        ],
    },
    {
        'author': 'tropical_fan',
        'title': '龟背竹叶片一直不开裂，养了一年还是心形叶，正常吗？',
        'content': '买回来的龟背竹一年了，新叶一直出但全是心形的，完全没有开裂的迹象。盆放在客厅散射光位置，定期浇水和施肥。网上说要养到一定龄才会裂叶，但也有人说跟光照和湿度有关。请问到底是什么原因？',
        'plant_type': '龟背竹',
        'status': 'answered',
        'view_count': 134,
        'is_urgent': False,
        'bounty': 20,
        'answers': [
            {
                'author': 'expert_foliage',
                'content': '龟背竹开裂叶确实和株龄、光照、支撑都有关系。幼株的前十几片叶子不裂是正常的。想加速的话可以给它搭攀爬柱，让气生根有附着点，同时保证稳定的散射光和足够的肥力。和自然环境中攀附在大树上的状态越接近，裂叶越早出现。',
                'is_accepted': True,
                'like_users': ['tropical_fan', 'fern_lover', 'green_thumb'],
            },
            {
                'author': 'fern_lover',
                'content': '我的龟背竹加了攀爬柱后，第三片新叶就开始出现分裂了。支撑确实有用。',
                'is_accepted': False,
                'like_users': ['tropical_fan'],
            },
        ],
    },
    {
        'author': 'night_grower',
        'title': '补光灯每天开多久合适？会不会打乱植物的生物钟？',
        'content': '最近买了一个全光谱补光灯给室内植物用，但不确定每天开多长时间合适。开太久怕对植物有害，开太短又没效果。家里散射光大概每天只有三四个小时。请问补光灯是白天开还是晚上也可以开？会不会影响植物的休息节律？',
        'plant_type': '室内植物',
        'status': 'answered',
        'view_count': 112,
        'is_urgent': False,
        'bounty': 15,
        'answers': [
            {
                'author': 'expert_foliage',
                'content': '观叶植物每天总光照时长在10到14小时之间就够了，算上自然光和补光灯加起来。建议补光灯在白天开，模拟自然光周期，晚上关掉让植物休息。连续24小时光照确实会打乱植物节律，尤其对短日照开花类植物影响更大。观叶类虽然耐受度更高，但也建议保持规律。',
                'is_accepted': True,
                'like_users': ['night_grower', 'tropical_fan', 'office_plant'],
            },
            {
                'author': 'tropical_fan',
                'content': '我的补光灯设了定时器，每天早8点到晚8点自动开关，运行了两个月效果很好。',
                'is_accepted': False,
                'like_users': ['night_grower'],
            },
        ],
    },
    {
        'author': 'rooftop_girl',
        'title': '天台盆栽铁线莲总是死苗，是不是盆太小了？',
        'content': '在天台用30cm口径的盆种了两棵铁线莲，品种是如梦和多蓝，种下去三个月后一棵枯死了，另一棵也很蔫。浇水施肥都没落下，光照也充足。朋友说铁线莲根系很大，30cm盆可能不够。是不是需要换更大的盆？',
        'plant_type': '铁线莲',
        'status': 'answered',
        'view_count': 99,
        'is_urgent': False,
        'bounty': 25,
        'answers': [
            {
                'author': 'expert_flower',
                'content': '铁线莲确实需要深盆，根系向下发展的空间很重要。建议至少用高40cm以上的深盆，口径30cm其实够的，但深度不能太浅。另外天台直晒+盆壁散热很快，夏天盆温很容易偏高导致根系受伤。盆外可以套一个隔热层或者放在不被阳光直射盆壁的位置。',
                'is_accepted': True,
                'like_users': ['rooftop_girl', 'balcony_garden', 'garden_dad'],
            },
            {
                'author': 'balcony_garden',
                'content': '我也是铁线莲新手，去年换了45cm深盆后存活率高了很多。浅盆确实是个坑。',
                'is_accepted': False,
                'like_users': ['rooftop_girl'],
            },
        ],
    },
    {
        'author': 'garden_dad',
        'title': '院子里的月季叶子被虫吃得全是洞，怎么判断是哪种虫？',
        'content': '院子里种的月季最近叶片出现了很多圆形或不规则的洞，有的叶片几乎被啃光了。白天没看到虫子，不知道是夜间活动的虫还是别的原因。花朵暂时没被影响，但叶片损失很大。怎么判断到底是什么虫在吃？',
        'plant_type': '月季',
        'status': 'answered',
        'view_count': 108,
        'is_urgent': True,
        'bounty': 30,
        'answers': [
            {
                'author': 'plant_doctor',
                'content': '圆形规整的洞通常是叶蜂（切叶蜂）造成的，它们切下叶片做巢，这种一般危害不大可以不管。不规则的洞可能是蛾类幼虫（如尺蠖、卷叶蛾）或金龟子，建议晚上打手电去查看，这些虫多数夜间活动。如果是蛾类幼虫，看到就手动清除或用生物杀虫剂处理。',
                'is_accepted': True,
                'like_users': ['garden_dad', 'expert_flower', 'rooftop_girl', 'balcony_garden'],
            },
            {
                'author': 'expert_flower',
                'content': '如果洞边缘很光滑整齐，大概率是切叶蜂，不会影响植株健康。如果边缘粗糙且叶片有卷曲，就要留意卷叶蛾幼虫了。',
                'is_accepted': False,
                'like_users': ['garden_dad', 'plant_doctor'],
            },
        ],
    },
    {
        'author': 'water_garden',
        'title': '水培植物的水里长了绿藻，对植物有害吗？怎么清理？',
        'content': '几个水培瓶最近水面和瓶壁上长了一层绿色的藻类，绿萝和铜钱草都有。换水后过几天又长出来。读到有人说藻类对植物无害，也有人说会争抢养分。想确认一下这到底有没有影响？有没有根治的方法？',
        'plant_type': '水培植物',
        'status': 'answered',
        'view_count': 115,
        'is_urgent': False,
        'bounty': 15,
        'answers': [
            {
                'author': 'expert_foliage',
                'content': '少量绿藻对植物几乎无害，但大量繁殖会和植物竞争养分、降低水中溶氧。根治方法是遮光——藻类需要光合作用，用不透光的容器或在瓶外套深色纸就能大幅抑制生长。另外控制营养液浓度也能减少藻类滋生。已经长了的，换水时用软刷刷干净瓶壁。',
                'is_accepted': True,
                'like_users': ['water_garden', 'green_thumb', 'office_plant'],
            },
            {
                'author': 'green_thumb',
                'content': '我后来全换成深色陶瓷瓶，藻类问题基本就解决了。透明玻璃瓶好看但容易长藻。',
                'is_accepted': False,
                'like_users': ['water_garden', 'office_plant'],
            },
        ],
    },
    {
        'author': 'orchid_lover',
        'title': '春兰迟迟不来花苞，是温差不够还是养分不足？',
        'content': '养了三年的春兰，叶片状态不错但从来没开过花。看资料说春兰需要秋冬的低温春化来分化花芽，但我在南方，冬天最低也就10度左右。用了兰花专用肥，生长正常就是不开花。是温差不够大还是养得太"舒服"了？',
        'plant_type': '春兰',
        'status': 'open',
        'view_count': 87,
        'is_urgent': False,
        'bounty': 25,
        'answers': [
            {
                'author': 'expert_flower',
                'content': '春兰确实需要一段低温期来促进花芽分化，一般要求秋冬有一到两个月的5到10度低温期，昼夜温差越大越好。南方冬天10度其实够用，关键是持续时间和不要在室内加温太高。另外夏季要适当控水控肥，让植株有"收紧"的信号，过于旺盛的营养生长反而抑制花芽。',
                'is_accepted': False,
                'like_users': ['orchid_lover', 'tropical_fan'],
            },
        ],
    },
    {
        'author': 'plant_doctor',
        'title': '橡皮树底部叶片一直掉，是正常老化还是有问题？',
        'content': '客厅里的橡皮树最近两个月底部叶片陆续黄落了五六片，顶部新叶倒是正常在长。整株看起来有点"光杆化"的趋势。浇水没太多变化，位置也没挪过。想确认一下这是正常的老叶代谢，还是根部或者环境有什么问题？',
        'plant_type': '橡皮树',
        'status': 'answered',
        'view_count': 93,
        'is_urgent': False,
        'bounty': 15,
        'answers': [
            {
                'author': 'expert_foliage',
                'content': '橡皮树底部老叶逐渐脱落是比较正常的生长规律，尤其是光照不均匀时底部叶片容易因光照不足而加速老化。如果掉叶速度不是特别快（一个月一两片属于正常范围），可以不用担心。想减缓光杆化，可以偶尔转盆让各面受光均匀，或者考虑春季打顶促侧枝。',
                'is_accepted': True,
                'like_users': ['plant_doctor', 'green_thumb', 'office_plant'],
            },
            {
                'author': 'green_thumb',
                'content': '我的橡皮树春天打顶后长出了三个侧芽，现在看起来丰满多了。打顶是解决光杆最有效的方法。',
                'is_accepted': False,
                'like_users': ['plant_doctor'],
            },
        ],
    },
    {
        'author': 'tiny_garden',
        'title': '多肉拼盆的品种搭配有讲究吗？习性差太大会不会互相干扰？',
        'content': '想做一个多肉拼盆，选了几个品种：薄雪万年草做铺面，黄丽和玉蝶做主角，加一棵小玉树做造型。但不确定这几个品种的浇水需求是不是差距太大，放在一个盆里会不会有的涝有的旱？拼盆有没有什么搭配原则？',
        'plant_type': '多肉',
        'status': 'answered',
        'view_count': 101,
        'is_urgent': False,
        'bounty': 15,
        'answers': [
            {
                'author': 'expert_succulent',
                'content': '拼盆最重要的原则是习性相近：光照需求、浇水频率、生长季节（春秋型或夏型）最好一致。你选的这几个品种都属于春秋型景天，习性比较接近，可以放在一起。注意用颗粒比例高的土壤，控水为主就行。唯一注意的是薄雪万年草长得快，可能会侵占其他品种的空间，定期修剪一下就好。',
                'is_accepted': True,
                'like_users': ['tiny_garden', 'succulent_fan', 'weekend_gardener', 'cactus_king'],
            },
            {
                'author': 'succulent_fan',
                'content': '千万别把夏型和冬型的放一盆，比如把玉露和芦荟拼在一起，浇水节奏完全相反会很痛苦。',
                'is_accepted': False,
                'like_users': ['tiny_garden', 'plant_lover1'],
            },
        ],
    },
]

__all__ = ['TOPIC_FOLLOW_SEEDS', 'POST_SEEDS', 'QUESTION_SEEDS']
